### ISSUE TITLE
Use the official github mirrors of GNOME and KDE instead of linking directly to their repos?

### ISSUE THREAD

**Issue by ghost** [opengaming/osgameclones#1002]
This would allow for the star counts of the repos on github, and since they're being officially maintained i figure that it wouldn't be a problem.

e.g. https://github.com/GNOME/quadrapassel instead of https://gitlab.gnome.org/GNOME/quadrapassel

**Comment by cxong** [comment]
github stars are nice but I think it's more important to link to the official repo rather than any mirrors. Looks like they are using gitlab which also has stars - hopefully there will be a gitlab stars badge soon.
