### ISSUE TITLE
Should we add Vangers?

### ISSUE THREAD

**Issue by ForNeVeR** [opengaming/osgameclones#1017]
[Vangers](https://github.com/KranX/Vangers) is not technically a clone/remake (because it builds on the original code base I believe), but it's a recently open-sourced old game that is being remade.

I'm not sure if it fits the rules and/or the spirit of the community here. What would you advise? Should we add it or not?

**Comment by cxong** [comment]
I think these can be added, using "remake" as the type
Additional info can be provided in the Info field
