### ISSUE TITLE
Add LBreakoutHD

### ISSUE THREAD

**Issue by jonadem** [opengaming/osgameclones#1022]
name: LBreakoutHD
originals:
- Arkanoid
type: clone
repo: 'https://sourceforge.net/p/lgames/code/HEAD/tree/'
url: 'http://lgames.sourceforge.net/LBreakoutHD/'
development: active
status: playable
multiplayer:
- Online
content: open
lang:
- C
- ' C++'
framework:
- SDL
license:
- GPL2
updated: '2019-12-26'
images:
- 'http://lgames.sourceforge.net/LBreakoutHD/ss2.jpg'

**Comment by cxong** [comment]
already added
