### ISSUE TITLE
Heart of darkness: Hode, wrong repo URL?

### ISSUE THREAD

**Issue by MBeijer** [opengaming/osgameclones#1054]
It feels like the repo URL for hode is wrong, it goes to tombexcavator currently, while this seems like a more appropriate URL: https://github.com/usineur/hode

Mistake or am I missing something? The tombexcavator repository doesn't seem to have anything to do with HODe.

**Comment by usineur** [comment]
The current URL you provided corresponds to a repo clone of the original sources, dedicated to my Playstation Vita and Nintendo Switch ports.

I suggest you to point to the author's original page: http://cyxdown.free.fr/hode/

**Comment by MBeijer** [comment]
@usineur Okay, thank you for clarifying!
