### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by CommonLoon102** [opengaming/osgameclones#1058]
Google is cancer.
Change it to something open source and tracking free, like goatcounter.com.

**Comment by wonea** [comment]
@CommonLoon102 @cxong I agree with the sentiment. Lets move to something less toxic.

**Comment by cxong** [comment]
This is up to @piranha I think

**Comment by piranha** [comment]
Why not, let's setup goatcounter and switch there? It's also going to be public, which is a good thing. :)

**Comment by piranha** [comment]
https://osgc.goatcounter.com/ :)

**Comment by wonea** [comment]
@piranha thank you so much! Makes our world a little better.
