### ISSUE TITLE
Github badges error out with 429 Too Many Requests

### ISSUE THREAD

**Issue by SupSuper** [opengaming/osgameclones#1080]
Loading the main page causes the Github badges to fail to load due to "too many requests":

![429 errors](https://user-images.githubusercontent.com/603444/78936725-088ff280-7aa7-11ea-8e71-961f59f05554.png)

Maybe they should just be replaced with a static link?

**Comment by cxong** [comment]
This should be fixed now that we have a rate limiter on badge requests
