### ISSUE TITLE
About Morrowind...

### ISSUE THREAD

**Issue by psi29a** [opengaming/osgameclones#1100]
All 3 listed under Morrowind are OpenMW, just that tes3mp is a long living branch of OpenMW that will eventually be merged in and OpenMicroWave is wrapper around OpenMW (making it a shared lib) with additional sauce on top specific for Android, but they upstream their work.

Perhaps it could be made clear that they are all OpenMW or based on OpenMW? Or perhaps something else?

**Comment by cxong** [comment]
yeah this can go in the `info:` field. When they are merged their entries can be removed too

**Comment by psi29a** [comment]
Why is it listed as halted?

**Comment by cxong** [comment]
last commit on any branch is from 7 months ago
