### ISSUE TITLE
Add entry for Open Solomon's Key

### ISSUE THREAD

**Issue by immortalx74** [opengaming/osgameclones#1108]
name: Open Solomon's Key
originals:
- Solomon's Key
type: clone
repo: 'https://github.com/mdodis/OpenSolomonsKey'
url: 'https://mdodis.itch.io/open-solomons-key'
development: very active
status: playable
lang:
- C++
license:
- Custom
images:
- 'https://img.itch.zone/aW1hZ2UvNjY2OTcwLzM2MDg3OTkuanBn/original/N0%2FGAU.jpg'

**Comment by pehsa** [comment]
Closed by #1119
