### ISSUE TITLE
Website not updated?

### ISSUE THREAD

**Issue by OmniBlade** [opengaming/osgameclones#1121]
I'm not sure what the normal time scale is from additions being merged into the repo and the go live, but it doesn't appear to me that the last tranch of additions/updates that were merged 2 weeks ago have gone live on the actual website?

**Comment by cxong** [comment]
cc @piranha 
https://travis-ci.org/github/opengaming/osgameclones/builds/712394137#L274
last deploy doesn't seem to have deployed to the main site

**Comment by piranha** [comment]
Eh somebody changed something and now it needs an option to be deployed. :\ Seems to be working [now](https://travis-ci.org/github/opengaming/osgameclones/builds/721304315). Had to click "resume auto deploys" in netlify interface, weird stuff.

I wonder if it makes sense to migrate from travis to github actions?

**Comment by piranha** [comment]
Closed by mistake. :-) Please look if everything looks ok? :)

**Comment by cxong** [comment]
lg2m
