### ISSUE TITLE
Free Heroes II update

### ISSUE THREAD

**Issue by hgdagon** [opengaming/osgameclones#1135]
The sourceforge project hasn't been updated in a long time. This is the continuation of the project:

https://github.com/ihhub/fheroes2

Before that we had Free heroes II Enhanced, but it's abandoned already:

https://github.com/ciplogic/fheroes2enh

The developer of enhanced moved on to JHeroes2X, a Java remake:

https://github.com/ciplogic/TilePainter

**Comment by cxong** [comment]
That last URL should be  https://github.com/ciplogic/fheroes2enh I guess

**Comment by hgdagon** [comment]
Not entirely sure what you mean, that's the second link I posted, the last one is the Java remake.

**Comment by cxong** [comment]
I'm not sure about adding the JHeroes2X one - it's ok to have unplayable games but I'm not certain of the state of that game. "TilePainter" suggests it's only one part of the game? Happy to add it once it has a better repo or website showing the whole game.
