### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#1153]
This year's hacktoberfest is opt-in; repos must add the `hacktoberfest` topic to have PRs count.
https://hacktoberfest.digitalocean.com/hacktoberfest-update

Should osgameclones participate? @piranha 

By the way, here's a list of games from our list that have the `hacktoberfest` topic:

- Ancient Beast https://github.com/FreezingMoon/AncientBeast
- C-Dogs SDL https://github.com/cxong/cdogs-sdl
- Cataclysm: Dark Days Ahead https://github.com/CleverRaven/Cataclysm-DDA
- EmptyEpsilon https://github.com/daid/EmptyEpsilon
- OpenLoco https://github.com/OpenLoco/OpenLoco
- OpenRA https://github.com/OpenRA/OpenRA
- OpenRCT2 https://github.com/OpenRCT2/OpenRCT2
- RuneLite https://github.com/runelite/runelite
- Space Station 14 https://github.com/space-wizards/space-station-14
- Terasology https://github.com/MovingBlocks/Terasology
- Unitystation https://github.com/unitystation/unitystation
- glPortal https://github.com/GlPortal/glPortal
- ioquake3 https://github.com/ioquake/ioq3
- osu! https://github.com/ppy/osu

And here's the script to find them (need to generate a personal access token and to install pygithub):

```
import re
import sys

from github import Github
from pathlib import Path

import yaml


REGEX = re.compile(r"https://github.com/([^/]+)/([^/]+)")


def main():
    g = Github(sys.argv[1])
    hacktober_games = {}
    for p in Path('games').iterdir():
        if p.is_file() and p.suffix == ".yaml":
            games = yaml.safe_load(open(p, encoding="utf-8"))
            for game in games:
                match = re.match(REGEX, game.get("repo", ""))
                if match:
                    owner, repo = match.groups()
                    topics = g.get_repo(f"{owner}/{repo}").get_topics()
                    if "hacktoberfest" in topics:
                        hacktober_games[game["name"]] = game
    for name, game in hacktober_games.items():
        print(name, game["repo"])


if __name__ == "__main__":
    main()

```

**Comment by piranha** [comment]
@cxong why not? :-) I mean, the only downside is that we can receive a spammy pull request, right? :)

**Comment by cxong** [comment]
Cool! Could you please add the topic? I'm not able to do so

**Comment by piranha** [comment]
Ah, I had no idea!
