### ISSUE TITLE
Augustus. Caesar 3 remake and fork of Julius.

### ISSUE THREAD

**Issue by Coockie** [opengaming/osgameclones#1181]
name: Augustus
originals:
- 'https://en.wikipedia.org/wiki/Caesar_III'
type: remake
repo: 'https://github.com/Keriew/augustus'
development: active
status: playable
content: commercial
lang:
- C
- C++
framework:
- SDL2
license:
- AGPL3
info:  Augustus is fork of Julius. When Julius provide vanilla experience of Caesar 3 with UI and visual enhancements and support for modern system and some bugfixes, while Augustus changes core gameplay that makes its game saves not compatible with original Caesar 3 and Julius games.
updated: '2020-11-16'
images:
- 'https://raw.githubusercontent.com/Keriew/augustus/master/res/vita/bg.png'

**Comment by axx0** [comment]
I think it should also be mentioned that Julius provides vanilla experience of Caesar 3 with UI and visual enhancements and support for modern systems, while Augustus changes core gameplay.

**Comment by Coockie** [comment]
> I think it should also be mentioned that Julius provides vanilla experience of Caesar 3 with UI and visual enhancements and support for modern systems, while Augustus changes core gameplay.

I think i mention about it now.
