### ISSUE TITLE
Minetest is listed as a Minecraft remake, however it is actually an Engine for Minecraft-like games

### ISSUE THREAD

**Issue by EliasFleckenstein03** [opengaming/osgameclones#1334]
You can list MineClone2 instead, which is a game based on the Minetest engine with 125k Downloads on ContentDB.
 Unlike most other games based on Minetest, MineClone2 aims to copy Minecraft Java Edition 1.12.2 as close as possible.

After trying out the other things listed as Minecraft clones / remakes, I noticed MineClone2 is actually the closest to a somewhat modern version of Minecraft, so it would definitely make sense to list it.

Repo: https://git.minetest.land/MineClone2/MineClone2
ContentDB Package: https://content.minetest.net/packages/Wuzzy/mineclone2/
Downloads: 125k
Development: Active
Language: Lua
Status: Playable
License: GPLv3
Framewok / Engine: Minetest

**Comment by EliasFleckenstein03** [comment]
Minetest is not a game. There is minetest_game which is the default Subgame for the Minetest engine, but Minetest itself cannot be launched without a Subgame. You could list minetest_game, but listing Minetest as a game is wrong. Minetest should appear as framework for MineClone2 and minetest_game.

**Comment by cxong** [comment]
These two games have been updated
