### ISSUE TITLE
Add NorseWorld: Ragnarok

### ISSUE THREAD

**Issue by SenhorFlibble** [opengaming/osgameclones#1372]
name: 'NorseWorld: Ragnarok'
originals:
- Ragnarok
- ' Valhalla'
type: remake
repo: 'https://github.com/Serg-Norseman/NorseWorld-Ragnarok'
url: 'https://sourceforge.net/projects/norseworld/'
development: halted
status: playable
content: free
lang:
- Java
license:
- GPL3

**Comment by Serg-Norseman** [comment]
👍
