### ISSUE TITLE
Add gitlab stars

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#1443]
Similar to github stars #682 , add stars for gitlab

A badge can be generated from (`silwol/freenukum` as example): `https://img.shields.io/badge/dynamic/json?color=green&label=gitlab%20stars&query=%24.star_count&url=https%3A%2F%2Fgitlab.com%2Fapi%2Fv4%2Fprojects%2Fsilwol%252Ffreenukum`
Where the project id needs to be URL encoded

Preview:
![](https://img.shields.io/badge/dynamic/json?color=green&label=gitlab%20stars&query=%24.star_count&url=https%3A%2F%2Fgitlab.com%2Fapi%2Fv4%2Fprojects%2Fsilwol%252Ffreenukum)

**Comment by tomrndom** [comment]
Hello! Can I work on this? I'm curious to see how to use python to generate the site

**Comment by cxong** [comment]
yes go ahead
check how the github stars were implemented
