### ISSUE TITLE
Update repos pointing to ftp:// endpoints

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#1466]
https://github.com/opengaming/osgameclones/search?q=ftp%3A%2F%2F

Some browsers don't support FTP and we are warning against it (see https://github.com/opengaming/osgameclones/issues/945)
Find existing repos that still point to ftp and update them to a more suitable location

**Comment by hansejo** [comment]
Looks like the final link in this entire repository is a dead link.
