### ISSUE TITLE
Enemy Engaged repository?

### ISSUE THREAD

**Issue by wonea** [opengaming/osgameclones#147]
Enemy Engaged was released as open source but have to join mailing list to get access to their GIT server. Unsure whether they want their GIT address public. Any comment?

http://eechcentral.simhq.com/index.php?title=Development

https://en.wikipedia.org/wiki/Enemy_Engaged:_RAH-66_Comanche_vs._KA-52_Hokum

Mantis - Enemy Engaged
http://bugs.enemyengaged.net/my_view_page.php

**Comment by nikuda** [comment]
This original source release. We don't have a way of marking it as such. I'd keep holding the addition until we have a way of designating original source releases from remakes/clones.

**Comment by nikuda** [comment]
Blocked by #533

**Comment by enemy-engaged-developers** [comment]
This repo isn't open source, please don't mark it as such.
