### ISSUE TITLE
Add WebQuake

### ISSUE THREAD

**Issue by dorr1** [opengaming/osgameclones#1476]
name: WebQuake
originals:
- Quake
type: remake
repo: 'https://github.com/Triang3l/WebQuake'
url: 'https://www.netquake.io/'
development: active
status: playable
content: commercial
lang:
- Javascript
framework:
- WebGL
license:
- GPL1
info: A web port of Quake. Works best on desktop Chrome and Firefox
updated: '2021-10-20'

**Comment by cxong** [comment]
URL is for a fork, which should be added as a different game
