### ISSUE TITLE
Add Serious-Sam-Android

### ISSUE THREAD

**Issue by dorr1** [opengaming/osgameclones#1497]
name: Serious-Sam-Android
originals:
- 'Serious Sam: the Second Encounter'
type: remake
repo: 'https://github.com/aarcangeli/Serious-Sam-Android'
development: halted
status: playable
content: commercial
lang:
- C++
- C
license:
- Custom
info: >-
  A port of Serious Sam: the Second Encounter to Android. There is also a fork
  for the Pandora.
updated: '2021-10-25'

**Comment by zetadeceleste** [comment]
Hello!
I added here: https://github.com/opengaming/osgameclones/pull/1508
