### ISSUE TITLE
Add Atom/RSS feed element to games

### ISSUE THREAD

**Issue by wonea** [opengaming/osgameclones#152]
We have a huge list of games, and I was thinking a news aggregator page would be great. Either in osgamesclones or through a sister site using a clone/linked repository. I would to create something minimal like this: 

http://planet-aros.heimstetten.net/

There's http://www.freegamealliance.com/ but I would like something more broad, based on the number of games we have.

As a first step can we add a NewsFeed: element to games.yaml for each game?

**Comment by piranha** [comment]
Adding an RSS feed is possible. Or do you think about something more general, like a 'news' section on a site?

**Comment by wonea** [comment]
If the News section used the feeds from the projects - there's a lot of activity if you add all the projects news together.

**Comment by piranha** [comment]
Hehe, I was talking about RSS with new games, not news of those games. :-)

**Comment by wonea** [comment]
Mmmmn, a new game feed would also be useful.

**Comment by tzizi** [comment]
This would likely require an extra property to be added to each game added/updated to the list, such as:

```
item-updated: 2018-07-24
```
