### ISSUE TITLE
Netlify deploy broken

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#1522]
@piranha need your help here; I don't know how netlify is set up

Recent deploys have been failing (since around 2021-11-09): https://app.netlify.com/sites/osgameclones/deploys

Fail message:
```
10:45:39 AM: Installing dependencies from Pipfile
10:45:39 AM: Traceback (most recent call last):
10:45:39 AM:   File "/opt/buildhome/python2.7/bin/pipenv", line 5, in <module>
10:45:39 AM:     from pipenv import cli
10:45:39 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/__init__.py", line 22, in <module>
10:45:39 AM:     from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
10:45:39 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
10:45:39 AM:     from .compat import (
10:45:39 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/vendor/vistir/compat.py", line 13, in <module>
10:45:39 AM:     from .backports.tempfile import NamedTemporaryFile as _NamedTemporaryFile
10:45:39 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/__init__.py", line 6, in <module>
10:45:39 AM:     from .tempfile import NamedTemporaryFile
10:45:39 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/tempfile.py", line 15, in <module>
10:45:39 AM:     from backports.weakref import finalize
10:45:39 AM: Creating deploy upload records
10:45:39 AM: ImportError: No module named weakref
10:45:39 AM: Error installing Pipenv dependencies
```

I don't know what the cause is, could have something to do with pipenv? The latest version broke the build, which I fixed by downgrading pipenv: https://github.com/opengaming/osgameclones/commit/a72508c44cb18640d9a4b229c60a13d0e8957569

Do we need to do the same thing for netlify? In their [changelog](https://github.com/netlify/build-image/blob/focal/CHANGELOG.md) they did not update pipenv but they do use the latest version, so the latest release (2021-11-08) might have bumped pipenv too.

**Comment by piranha** [comment]
So okay in the end it turns out Netlify already introduced Ubuntu 20.04 to their builds. But for the existing project to switch it needed to be done manually. The only Python 3 version [it supports](https://github.com/netlify/build-image/blob/focal/included_software.md) is 3.8.

I did that and now it fails on "No module named 'pip._vendor.certifi'" wtf. Internet says upgrading pip will help, but Netlify installs stuff from Pipenv before running anything from me so I'm not sure how to force them to update pip. :\

**Comment by cxong** [comment]
We could try downgrading to xenial and using runtime.txt to specify version 3.7, like in this PR: https://github.com/opengaming/osgameclones/pull/1525

**Comment by piranha** [comment]
🤦  IDK wtf is going on. Maybe it's time to go from Pipenv to some greener pastures haha, I'll ask my friends around on what's the proper approach.

I'd prefer to update to 20.04 because I feel like xenial could be deprecated any time soon.

**Comment by cxong** [comment]
@piranha could you add me to your netlify team? I can take a look at the setup. For an alternative to pipenv, poetry might be a good.

**Comment by piranha** [comment]
Unfortunately adding more members costs money :(

Sorry, I've been somewhat busy with Black Friday stuff here (you know ecommerce is tough during november haha). Poetry sounds interesting, I'll try to switch, maybe it'll work!

**Comment by piranha** [comment]
#1535 fixes build. I guess poetry is ok. :)
