### ISSUE TITLE
add "type: Official" (or similar)

### ISSUE THREAD

**Issue by kparal** [opengaming/osgameclones#1554]
I believe that osgameclones is sorely missing a way to mark official source code releases. For example, I recently hit the issue with Little Big Adventure:
https://github.com/opengaming/osgameclones/discussions/1504

And a few days back, Two Tribes open sourced their engine:
https://www.gamingonlinux.com/2021/12/two-tribes-open-sourced-their-game-engine-for-rive-and-toki-tori-2-/

Marking those code releases as remakes is confusing and misleading. I believe there should be a new `type` for these cases, e.g. `type: Official` (or something similar).

I'm sure there are many more cases where this new type could be applied, but just to name a few:
https://github.com/jmechner/Prince-of-Persia-Apple-II
https://github.com/TwoTribesGames/ttengine
https://github.com/2point21/lba1-classic
https://github.com/2point21/lba1-classic-community  (this could be possibly labeled as a remake, if community starts to make extensive changes)
https://gitlab.com/osslugaru/lugaru
https://github.com/TerryCavanagh/vvvvvv
https://github.com/electronicarts/CnC_Remastered_Collection
https://github.com/DataRealms/CCOSS
https://github.com/id-Software/DOOM
http://blog.wolfire.com/2010/05/Gish-goes-open-source
https://github.com/viewizard/astromenace

What do you think?

**Comment by cxong** [comment]
I think this is a good idea.

Earlier related discussion: https://github.com/opengaming/osgameclones/issues/533

I'm against adding a "source port" type, because if the changes become extensive, the type becomes less meaningful. But not so for "official"; to players it says that the gameplay should be exactly the same as the original game, and for developers it says that the goal of the project is to avoid gameplay changes.

If the project accumulates enough gameplay changes it could change from "official" to "remake".

**Comment by nextghost** [comment]
To me, "official" implies that the repository is maintained by the original developers or at least the current brand owner. I'd suggest two types for projects based on the original sources:
- `source_port` - the project offers (or aims to offer in the future) more or less the original game experience with some optional changes on the side
- `source_mod` - the project is based on the original sources but the gameplay has been substantially changed and there's no intent to provide a "vanilla" mode that would offer the original experience

**Comment by kparal** [comment]
> To me, "official" implies that the repository is maintained by the original developers or at least the current brand owner.

That's exactly what I meant, and I believe that's the case for all the examples I listed.

**Comment by cxong** [comment]
Just wanted to point out `official` should not be used to add games that were always open source; that is outside the scope of OSGC.
