### ISSUE TITLE
Filters return zero results

### ISSUE THREAD

**Issue by laenion** [opengaming/osgameclones#1591]
When clicking on any of the filters, e.g. the _Type_ filter (_Remake_, _Clone_, ...) or the filters on the top (_Languages_, _Genres_, _Subgenres_ etc.) the filters are only applied to the _New and updated games_ list, the main list however will always be empty after that.

When typing in a filter manually in the upper left left box however the filter will be applied correctly.

**Comment by MajickTek** [comment]
This really should be fixed, it's been like this for months

**Comment by caiotava** [comment]
This PR will fix this issue: https://github.com/opengaming/osgameclones/pull/1614

**Comment by laenion** [comment]
Confirming fix. Thanks a lot!
