### ISSUE TITLE
Add OpenTyrian2000

### ISSUE THREAD

**Issue by Foroneus** [opengaming/osgameclones#1665]
name: OpenTyrian2000
originals:
- Tyrian2000
type: remake
url: 'https://github.com/KScl/opentyrian2000'
feed: 'https://github.com/KScl/opentyrian2000/releases'
development: active
status: playable
multiplayer:
- Online
- LAN
content: open
lang:
- C
license:
- GPL2
info: Port of OpenTyrian made to support Tyrian2000/
updated: '2022-04-01'

**Comment by cxong** [comment]
I think we can add "Tyrian 2000" as an alternate name for Tyrian since it's a rerelease with an additional campaign
