### ISSUE TITLE
Add RTDink

### ISSUE THREAD

**Issue by kparal** [opengaming/osgameclones#1819]
**RTDink** is an _official_ open source version (developed by the same author) of **Dink Smallwood** from 1997.

Homepage: https://www.rtsoft.com/pages/dink.php
Project development: https://github.com/SethRobinson/RTDink

It's even offered by GOG:
https://www.gog.com/game/dink_smallwood_hd

**Comment by kparal** [comment]
While the repository is called **RTDink**, the project seems to called **Dink Smallwood HD** officially everywhere else, so perhaps listing both names is a good idea, or just the "HD" one.

**Comment by cxong** [comment]
I think this should be a remake instead of official; the authorship is not important, it's the fact that it uses different assets and code. For example we would refer to Age of Empires HD / DE, or Command and Conquer Remastered as remakes, despite being made by the same copyright owners.
