### ISSUE TITLE
Incorrect listing of the Zelda: Ocarina of Time decompilation project?

### ISSUE THREAD

**Issue by romatthe** [opengaming/osgameclones#1826]
It seems the [Ocarina of Time decompilation project](https://github.com/zeldaret/oot) was [added to the list](https://github.com/opengaming/osgameclones/blob/07f1230477cc57bb32d47631b67ef095b021ff6d/games/l.yaml#L214) here, but I believe it is either incorrectly tagged, or should be removed.

As is clearly visible, it is tagged as `status: playable`. However, the project itself doesn't really provide a complete and working PC port to play around with. It leaves that work up to downstream project as far as I can tell.

Here's what the project itself has to say about this:
> This is a WIP decompilation of The Legend of Zelda: Ocarina of Time. The purpose of the project is to recreate a source code base for the game from scratch, using information found inside the game along with static and/or dynamic analysis. It is not producing a PC port.

I think this should either be tagged as `status : unplayable` or removed outright, since the project's scope doesn't really include producing a functioning game. Maybe I'm taking a view of the tags that's a little bit too narrow, but I also think it might provide a misrepresentation of what the `oot` project actually contains.

Incidentally, I've added a PR (#1825) for Ship of Harkinian, a project that actually does provide a working PC port based on the decompilation project.

Just my two cents.

**Comment by cxong** [comment]
Yes it should be unplayable
