### ISSUE TITLE
Pull request fails: online form format incorrect, and build can't create new "original game"?

### ISSUE THREAD

**Issue by cricri-pingouin** [opengaming/osgameclones#1877]
I tried to fork, use the web form,and when copy/pasting into the yaml file, the output does not seem tabulated properly and pull request fails?

I only changed s.yaml:
https://github.com/cricri-pingouin/osgameclones

I manually edited the output to try to correct the format and thought my 3rd pull would be ok, but if the "original game" does not already exist, "build and deploy" fails?

` SliLights
Original game 'Lights Out' not found
SliMind
Original game 'Mastermind' not found
SliPeg
Original game 'Peg Solitaire' not found
SliSame
Original game 'Same Game' not found

4 errors

make: *** [Makefile:4: run] Error 1
Error: Process completed with exit code 2.`

**Comment by cxong** [comment]
original game definitions are in the `/originals` YAML files

**Comment by cricri-pingouin** [comment]
Ah, right, that makes sense. Sorry for misunderstanding how the whole thing works.
I just used the online form to create my records, and the pull request just kept failing miserably.

**Comment by cricri-pingouin** [comment]
Ok, still not sure how those pull requests are supposed to work. I still get:

   SliLights
    Original game 'Lights Out' not found
  SliMind
    Original game 'Mastermind' not found
  SliPeg
    Original game 'Peg Solitaire' not found

I thought those pulls for originals/*.yaml were already completed successfully. Apparently not. So my pull request for games/s.yaml still fails, despite using the correct format for all additions.

**Comment by cricri-pingouin** [comment]
Those are the games I tried to add by the way, all in s.yaml:

`- name: SliJewel
  originals:
  - Bejeweled
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliJewel'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Bejeweled game clone written in Turbo Delphi. Configurable board size and number of colours.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81442796-26b34600-916c-11ea-87ed-c44b69d627f9.png'

- name: SliLights
  originals:
  - Lights Out
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliLights'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Lights Out game clone written in Turbo Delphi. 100 levels built in (50 classic + 50 Lights Out 2000) and random levels generator.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/94176651-4edbe100-fe90-11ea-80c1-e5adc69b3a50.png'

- name: SliLumns
  originals:
  - Columns
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliLumns'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Columns game clone written in Turbo Delphi. Configurable starting difficulty and speed.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81442889-56fae480-916c-11ea-8f29-5567d4d4a2ae.png'



- name: SliMind
  originals:
  - Mastermind
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliMind'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Master Mind game clone written in Turbo Delphi. Configurable number of pegs, colours, max attempts, repeat colours yes/no.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81473895-c66ae580-91f9-11ea-9dad-30216f750818.png'

- name: SliMine
  originals:
  - Minesweeper
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliMine'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Minesweeper game clone written in Turbo Delphi. Configurable board size and number of mines.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81442492-98d75b00-916b-11ea-9660-6e55f1949557.png'

- name: SliPeg
  originals:
  - Peg Solitaire
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliPeg'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Peg Solitaire game clone written in Turbo Delphi. English and European boards.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81443347-2cf5f200-916d-11ea-8f25-5a3db86b7749.png'

- name: SliSame
  originals:
  - Same Game
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliSame'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Same Game clone written in Turbo Delphi. Configurable number of colours and board size.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81443622-a7bf0d00-916d-11ea-9e60-f4d2b672943f.png'

- name: SliSnake
  originals:
  - Snake
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliSnake'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Snake game clone written in Turbo Delphi. Configurable room size and speed, joystick support.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81443921-359af800-916e-11ea-841b-efdf9ae4ede0.png'

- name: SliTris
  originals:
  - Tetris
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliTris'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Tetris game clone written in Turbo Delphi. Configurable starting difficulty and speed.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81442665-efdd3000-916b-11ea-8aba-af1efc3e6b96.png'
`

**Comment by cricri-pingouin** [comment]
```
- name: SliJewel
  originals:
  - Bejeweled
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliJewel'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Bejeweled game clone written in Turbo Delphi. Configurable board size and number of colours.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81442796-26b34600-916c-11ea-87ed-c44b69d627f9.png'

- name: SliLights
  originals:
  - Lights Out
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliLights'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Lights Out game clone written in Turbo Delphi. 100 levels built in (50 classic + 50 Lights Out 2000) and random levels generator.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/94176651-4edbe100-fe90-11ea-80c1-e5adc69b3a50.png'

- name: SliLumns
  originals:
  - Columns
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliLumns'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Columns game clone written in Turbo Delphi. Configurable starting difficulty and speed.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81442889-56fae480-916c-11ea-8f29-5567d4d4a2ae.png'



- name: SliMind
  originals:
  - Mastermind
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliMind'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Master Mind game clone written in Turbo Delphi. Configurable number of pegs, colours, max attempts, repeat colours yes/no.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81473895-c66ae580-91f9-11ea-9dad-30216f750818.png'

- name: SliMine
  originals:
  - Minesweeper
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliMine'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Minesweeper game clone written in Turbo Delphi. Configurable board size and number of mines.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81442492-98d75b00-916b-11ea-9660-6e55f1949557.png'

- name: SliPeg
  originals:
  - Peg Solitaire
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliPeg'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Peg Solitaire game clone written in Turbo Delphi. English and European boards.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81443347-2cf5f200-916d-11ea-8f25-5a3db86b7749.png'

- name: SliSame
  originals:
  - Same Game
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliSame'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Same Game clone written in Turbo Delphi. Configurable number of colours and board size.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81443622-a7bf0d00-916d-11ea-9e60-f4d2b672943f.png'

- name: SliSnake
  originals:
  - Snake
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliSnake'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Snake game clone written in Turbo Delphi. Configurable room size and speed, joystick support.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81443921-359af800-916e-11ea-841b-efdf9ae4ede0.png'

- name: SliTris
  originals:
  - Tetris
  type: remake
  repo: 'https://github.com/cricri-pingouin/SliTris'
  development: complete
  status: playable
  content: free
  langs:
  - Delphi
  licenses:
  - GPL3
  info: 'A Tetris game clone written in Turbo Delphi. Configurable starting difficulty and speed.'
  updated: '2022-10-17'
  images:
  - 'https://user-images.githubusercontent.com/64480118/81442665-efdd3000-916b-11ea-8aba-af1efc3e6b96.png'

```
