### ISSUE TITLE
Add ScummVM-supported games

### ISSUE THREAD

**Issue by kparal** [opengaming/osgameclones#1910]
Quite surprisingly, [ScummVM](https://www.scummvm.org/)-supported games are completely missing in OSGC, with an exception of the _Blade Runner_. There is a catch-all entry named _SCUMM_, but that probably won't help much to a general reader. If people search e.g. for _The Secret of Monkey Island_ or _Simon the Sorcerer_, they'll have no idea that there actually **is** an opensource project which can run those old games.

I understand that it's a lot of work, but I think the best approach (for readers) is to make an entry for all [ScummVM-supported games](https://www.scummvm.org/compatibility/) in OSGC.

**Comment by hendursaga** [comment]
Duplicate of #1818 perhaps?
