### ISSUE TITLE
Add AJ Classic, Fer.al

### ISSUE THREAD

**Issue by SuperWillow** [opengaming/osgameclones#1917]
Добавьте на сайт, хотя-бы AJ Classic и Fer.al
Вот их коды:
name: Animal Jam Classic (AJ Classic)
names:
- AJ Classic
external:
  website: classic.animaljam.com
  wikipedia: Animal Jam Classic
platforms:
- Windows
meta:
  genres:
  - Adventure
  - Educational
  - MMORPG
Это AJ Classic, а вот Fer.al:
name: Fer.al
names:
- Feral
external:
  website: fer.al/en
platforms:
- Android
- iOS
- OSX
- Windows
meta:
  genres:
  - Adventure
  - MMORPG
  themes:
  - Fantasy
Спасибо, что прочитали:)

**Comment by SuperWillow** [comment]
@cxong, вы точно добавите Fer.al Rewritted, как только установщик игры появится. Я не могу дождаться...

**Comment by cxong** [comment]
sure; happy to add it when there are clones

**Comment by SuperWillow** [comment]
@cxong клонов игр AJ Classic, Fer.al ещё нету, так как они ещё не вышли. А пока что, жду...

**Comment by SuperWillow** [comment]
Я уже работаю над клоном Fer.al:)
