### ISSUE TITLE
Add Wobbledogs

### ISSUE THREAD

**Issue by SuperWillow** [opengaming/osgameclones#1931]
Спасибо, что AJ Classic и Fer.al пока еще не добавлены, но добавьте ориг. игру Wobbledogs. Жаль, что у этой игры нет клонов или движков, которые требуют оригинальные  файлы игры, вроде например Jazz² Resurrection, Julius и Project FreeSims, CorsixTH. Можно хотя-бы их добавить?
Вот код: 
name: Wobbledogs
external:
  website: 'https://wobbledogs.com/'
platforms:
- Linux
- OSX
- Windows
meta:
  genres:
  - Simulation
  subgenres:
  - Life

**Comment by cxong** [comment]
The purpose of OSGC is to show open source clones; if we add only the original game, nothing will be shown on the website, so there is no point

**Comment by SuperWillow** [comment]
@cxong, извини что нету клона игры Wobbledogs:( Но можно потом немного подумать... И еще раз Thank you
