### ISSUE TITLE
OpenDungeons has an active fork "OpenDungeons Plus"

### ISSUE THREAD

**Issue by stepo2** [opengaming/osgameclones#2063]
OpenDungeons having the tag "sporadic development" is pretty optimistic, IMHO (there's bascially only some yearly commits to be able to still be able to compile the code for latest Ubuntu), last actual release was 2016.

However, there's an active fork with actual new features: OpenDungeons Plus.
* https://github.com/tomluchowski/OpenDungeonsPlus
* https://snapcraft.io/opendungeons-plus

I think the OpenDunegons entry should be updated (development "halted" and new active fork).

**Comment by cxong** [comment]
OpenDungeons has had a bug fix commit in Jan but I see the description contains "*Not actively developed anymore*" so halted is right
