### ISSUE TITLE
Transfer osgc to Github Pages

### ISSUE THREAD

**Issue by piranha** [opengaming/osgameclones#2109]
Hey! While Netlify works, I've been thinking if moving to Github Pages makes sense. First, deploy will be in Github Actions, so less places to search for stuff if anything breaks. Second, I still can't add members without paying Netlify money.

So what do you think @cxong? I'll do the work if you think it makes sense.

**Comment by cxong** [comment]
Yes this sounds good! I have a project that also uses github pages to deploy, it works well https://github.com/cxong/tic-80-examples

**Comment by piranha** [comment]
Done! :) Domain's been redirected, HTTPS is working fine, deploy is working fine too.
