### ISSUE TITLE
Add restunts

### ISSUE THREAD

**Issue by neuromancer** [opengaming/osgameclones#2118]
https://github.com/xor2003/restunts

**Comment by xor2003** [comment]
Hey it is unfinished. Also I just copied the repo.

**Comment by neuromancer** [comment]
It is still ok if it is unfinished. Which is the original repository? We should link that one, unless it is unmaintained and you are working on it.

**Comment by xor2003** [comment]
https://forum.stunts.hu/index.php?board=90.0

**Comment by LowLevelMahn** [comment]
its not an open source game clone - its the 1:1 reverse engineered game code to assembler with some functions replaced with C
