### ISSUE TITLE
Add HPL1 Engine for Penumbra series

### ISSUE THREAD

**Issue by kparal** [opengaming/osgameclones#2261]
There's an official source code for _HPL1 Engine_ which is used in the [Penumbra series](https://www.mobygames.com/group/8182/penumbra-series/) (i.e. Overture, Black Plague and Requiem) here:
https://github.com/FrictionalGames/HPL1Engine

**Comment by cxong** [comment]
I'm not sure this should be added; it is a dependency of other games like Penumbra Overture, which requires HPL1 here: https://github.com/FrictionalGames/PenumbraOverture/blob/master/CMakeLists.txt#L5

**Comment by kparal** [comment]
Yes, I wasn't sure either when creating this. Technically it probably shouldn't matter whether the game source code is all in one place, or whether it's split between a game-specific code and a shared engine code. But practically it could make the current web navigation more difficult/confusing.
