### ISSUE TITLE
Hacktoberfest 2023

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#2295]
Here are the projects listed on OSGC participating in hacktoberfest:

- [**Laser Kombat** ![stars](https://img.shields.io/badge/github%20stars-8-blue)](https://github.com/sharkwouter/laserkombat): (sporadic playable `C++` `SDL2`)
- [**UltraStar Play** ![stars](https://img.shields.io/badge/github%20stars-333-blue)](https://github.com/UltraStar-Deluxe/Play): (sporadic playable `C#` `Unity`)
- [**Unitystation** ![stars](https://img.shields.io/badge/github%20stars-692-blue)](https://github.com/unitystation/unitystation): (very active playable `C#` `Unity`)
- [**Ancient Beast** ![stars](https://img.shields.io/badge/github%20stars-1438-blue)](https://github.com/FreezingMoon/AncientBeast): (active playable `JavaScript` `Phaser`)
- [**Terasology** ![stars](https://img.shields.io/badge/github%20stars-3562-blue)](https://github.com/MovingBlocks/Terasology): (active playable `Java` )
- [**Minetest** ![stars](https://img.shields.io/badge/github%20stars-9459-blue)](https://github.com/minetest/minetest): (active playable `C`, `C++`, `Lua` )
- [**Space Nerds In Space** ![stars](https://img.shields.io/badge/github%20stars-693-blue)](https://github.com/smcameron/space-nerds-in-space): (active playable `C` `SDL2`, `OpenGL`)
- [**Space Station 14** ![stars](https://img.shields.io/badge/github%20stars-1592-blue)](https://github.com/space-wizards/space-station-14): (very active playable `C#` )
- [**SuperTux** ![stars](https://img.shields.io/badge/github%20stars-1656-blue)](https://github.com/SuperTux/supertux): (active playable `C++` `SDL2`)
- [**freegish** ![stars](https://img.shields.io/badge/github%20stars-61-blue)](https://github.com/freegish/freegish): (active playable `C` `SDL`, `OpenGL`)
- [**Jagged Alliance 2 Stracciatella** ![stars](https://img.shields.io/badge/github%20stars-414-blue)](https://github.com/ja2-stracciatella/ja2-stracciatella): (active playable `C++`, `C` )
- [**glPortal** ![stars](https://img.shields.io/badge/github%20stars-342-blue)](https://github.com/GlPortal/glPortal): (halted playable `C++` )
- [**DevilutionX** ![stars](https://img.shields.io/badge/github%20stars-7190-blue)](https://github.com/diasurgical/devilutionX): (active playable `C++` `SDL`, `SDL2`)
- [**doukutsu-rs** ![stars](https://img.shields.io/badge/github%20stars-718-blue)](https://github.com/doukutsu-rs/doukutsu-rs): (active playable `Rust` )
- [**Hishigata** ![stars](https://img.shields.io/badge/github%20stars-42-blue)](https://github.com/LumpBloom7/hishigata): (sporadic playable `C#` `osu!framework`)
- [**ioquake3** ![stars](https://img.shields.io/badge/github%20stars-2201-blue)](https://github.com/ioquake/ioq3): (active playable `C` `SDL2`)
- [**PySol Fan Club edition** ![stars](https://img.shields.io/badge/github%20stars-408-blue)](https://github.com/shlomif/PySolFC): (active playable `Python` `GTK`)
- [**Bemuse** ![stars](https://img.shields.io/badge/github%20stars-1074-blue)](https://github.com/bemusic/bemuse): (sporadic playable `JavaScript`, `TypeScript` )
- [**Bobby** ![stars](https://img.shields.io/badge/github%20stars-10-blue)](https://github.com/yannicka/bobby): (halted playable `TypeScript` )
- [**Word War vi** ![stars](https://img.shields.io/badge/github%20stars-99-blue)](https://github.com/smcameron/wordwarvi): (complete playable `C` )
- [**C-Dogs SDL** ![stars](https://img.shields.io/badge/github%20stars-782-blue)](https://github.com/cxong/cdogs-sdl): (sporadic playable `C` `SDL2`)
- [**Cataclysm: Dark Days Ahead** ![stars](https://img.shields.io/badge/github%20stars-8879-blue)](https://github.com/CleverRaven/Cataclysm-DDA): (active playable `C++`, `Lua` `ncurses`)
- [**OceanPop** ![stars](https://img.shields.io/badge/github%20stars-22-blue)](https://github.com/sharkwouter/oceanpop): (active playable `C++` )
- [**openage** ![stars](https://img.shields.io/badge/github%20stars-12007-blue)](https://github.com/SFTtech/openage): (active semi-playable `C++`, `Python` `SDL`, `OpenGL`)
- [**OpenLoco** ![stars](https://img.shields.io/badge/github%20stars-1053-blue)](https://github.com/OpenLoco/OpenLoco): (active playable `C++` )
- [**OpenRA** ![stars](https://img.shields.io/badge/github%20stars-13447-blue)](https://github.com/OpenRA/OpenRA): (active playable `C#`, `Lua` `.NET`, `SDL2`, `OpenAL`, `OpenGL`)
- [**OpenRCT2** ![stars](https://img.shields.io/badge/github%20stars-12290-blue)](https://github.com/OpenRCT2/OpenRCT2): (active playable `C++` )
- [**osu!** ![stars](https://img.shields.io/badge/github%20stars-12972-blue)](https://github.com/ppy/osu): (active playable `C#` `.NET`)

**Comment by ARTICFOX1234** [comment]
I am interested
