### ISSUE TITLE
Fix Python 3.12 Support

### ISSUE THREAD

**Issue by hendursaga** [opengaming/osgameclones#2336]
Thanks to [Python 3.12 removing distutils](https://docs.python.org/3.12/whatsnew/3.12.html), I cannot run make anymore:

```
$ make
poetry run python render.py
Traceback (most recent call last):
  File "<dir>/osgameclones/render.py", line 10, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'
make: *** [Makefile:4: run] Error 1
```

**Comment by cxong** [comment]
I tried upgrading past 3.8 at some point but the web host did not support it, not sure if this has changed @piranha

**Comment by cxong** [comment]
#1522 - it was netlify which we don't use anymore so I guess we can give this a try again? Will need to check if all the dependencies support 3.12
