### ISSUE TITLE
Add Just Shapes & Beats 

### ISSUE THREAD

**Issue by SuperWillow** [opengaming/osgameclones#2386]
Можете добавить на этот сайт мою любимую игру, тем не более она относится к буллет-хеллу и ритм-играм. На сайте тут лишь один буллет хелл и маленькое количество ритм игр, поэтому стоит её добавить!

Вот кстати, код:
name: Just Shapes & Beats
external:
  website: 'https://justshapes&beats.com/'
  wikipedia: Just Shapes & Beats
platforms:
- Nintendo Switch
- PlayStation 4
- Windows
- Xbox Series S/X
meta:
  genres:
  - Rhythm
  - Shmup
  subgenres:
  - Bullet Hell

**Comment by cxong** [comment]
Hi, thanks for posting. Please note however that even if this is added, it won't be shown in the website, because this website lists clones of games - if a game has no clones, it won't be shown!
