### ISSUE TITLE
Add Vib-Ribbon

### ISSUE THREAD

**Issue by SuperWillow** [opengaming/osgameclones#2387]
Вслед за JSAB, попробую сделать так, чтобы на этот сайт выложили и другую игру.

name: Vib Ribbon
external:
  wikipedia: Vib Ribbon
platforms:
- PlayStation
- PlayStation 3
- PlayStation 4
- PlayStation Vita
- PSP
meta:
  genres:
  - Platform
  - Rhythm

**Comment by cxong** [comment]
Hi, thanks for posting. Please note however that even if this is added, it won't be shown in the website, because this website lists clones of games - if a game has no clones, it won't be shown!
