### ISSUE TITLE
Add Vib Ribbon Minus

### ISSUE THREAD

**Issue by SuperWillow** [opengaming/osgameclones#2389]
А теперь добавьте ремейк Vib-Ribbon, раз он уже есть.

Код:

name: Vib Ribbon Minus
originals:
- Vib Ribbon
type: remake
repo: 'https://github.com/PlayNowKnux/VibRibbonMinusRelease'
url: 'https://github.com/PlayNowKnux/VibRibbonMinusRelease/releases'
development: complete
status: playable
content: open
langs:
- Python
licenses:
- Apache
info: A remake of the original Vib-Ribbon game with 2D graphics and custom tracks.
updated: '2022-08-03'

**Comment by cxong** [comment]
#2387

**Comment by SuperWillow** [comment]
Спасибо тебе за помощь, @cxong! Всё таки Vib-Ribbon помимо этого ремейка выходил в 1999-2000 годах. Спасибо, что ты добавил Vib Ribbon Minus вместе с оригинальной игрой:)
