### ISSUE TITLE
Streets of Rage 2

### ISSUE THREAD

**Issue by star69rem** [opengaming/osgameclones#2393]
name: Streets of Rage 2 New Era
originals:
- Streets of Rage 2
type: remake
url: 'https://www.sor2newera.com/'
development: very active
status: playable
multiplayer:
- Local
- Online
- Co-op
content: free
langs:
- 'C#'
frameworks:
- Unity
licenses:
- Custom
updated: '2023-12-25'

**Comment by cxong** [comment]
I could not find its source code, so we cannot add this
