### ISSUE TITLE
Add "Oni"

### ISSUE THREAD

**Issue by Lifell** [opengaming/osgameclones#2404]
Oni is an old game by Bungie. Source code was released some time ago.

https://archive.org/details/oni-source

https://github.com/hogsy/OniFoxed
"This is a modified variant of the recently leaked [Oni source code](https://archive.org/details/oni-source) so that it compiles under Microsoft Visual Studio 2019 with some minor fixes/changes."

**Comment by cxong** [comment]
I don't think we should add this game. The legality of the source code is unclear.
