### ISSUE TITLE
Add Roblox

### ISSUE THREAD

**Issue by ElPro7777** [opengaming/osgameclones#2420]
name: Roblox
external:
  website: www.roblox.com
  wikipedia: 'https://wikipedia.org/wiki/Roblox'
platforms:
- Android
- Mobile
- Nintendo Switch
- PlayStation 3
- PlayStation 4
- PlayStation 5
- Windows
- Xbox One
- Xbox Series S/X
meta:
  genres:
  - MMORPG
  subgenres:
  - Sandbox

**Comment by cxong** [comment]
there is no clone for this game - will not add
