### ISSUE TITLE
Add MS-Engine (Diggers, 1993)

### ISSUE THREAD

**Issue by neuromancer** [opengaming/osgameclones#2464]
https://github.com/XMhat/MSEngine/tree/master/diggers

(Keep in mind it uses a custom license)

**Comment by Mhatxotic** [comment]
Link has been updated to https://github.com/Mhatxotic/Engine/tree/master/diggers and is now called Mhatxotic Engine.

**Comment by Mhatxotic** [comment]
Link has been updated to https://github.com/Mhatxotic/Engine/tree/master/diggers and is now called Mhatxotic Engine.
