### ISSUE TITLE
Add Atomic Bomberman, FreePascal version

### ISSUE THREAD

**Issue by PascalCorpsman** [opengaming/osgameclones#2559]
The game Atomic Bomberman is still existing: https://osgameclones.com/atomic-bomberman/

I created a new Port, that looks nearly 100% like the original from 1997 and is complete opensource. This same look is due to the fact, that it uses the original images. So in order to get a playable game you need to have the original Disk content (which can be downloaded through the internet) or copied from the original disk. 

https://github.com/PascalCorpsman/fpc_atomic

**Comment by PascalCorpsman** [comment]
![In_Game](https://github.com/opengaming/osgameclones/assets/73154490/8050412a-c8ce-406c-9efe-6c673f4da760)
![Main_Screen](https://github.com/opengaming/osgameclones/assets/73154490/0837be01-2ad9-4011-b3b1-c54f4b58a513)

Unfortunatunelly i am not able to record my screen, but i made you two screenshots ;)

**Comment by PascalCorpsman** [comment]
[FPC_Atomic_Preview.zip](https://github.com/user-attachments/files/15520898/FPC_Atomic_Preview.zip)

Finally was able to make a screenrecord of it, hat to zip it to upload it ;)

**Comment by kparal** [comment]
I think @cxong meant publicly accessible screenshots (like from the github page) and videos (e.g. on youtube), so that he can link it from osgameclones.com. It's something that probably any visitor of your project would appreciate to see.

Btw, the game looks and seems to play like the original, many thanks for your work.

**Comment by PascalCorpsman** [comment]
I would love to add screenshots and videos, but i am not shure weather this is allowed, as i could not find any informations about the copyrights of the source images / sounds (i know that there are a lot of projects out there that don't care for that, but i care). Thats the reason why the game comes with the cd_data_extractor. If you own the original CD (as i do) then it is easy to create a running game with that application (its the same thechnic that was used for OpenTTD and OpenRA)..
