### ISSUE TITLE
Hunter (Amiga & Atari)

### ISSUE THREAD

**Issue by wonea** [opengaming/osgameclones#274]
Found a remake of [Hunter ]([url]%28https://en.wikipedia.org/wiki/Hunter_%28video_game%29%29)for Unity

http://www.indieretronews.com/2015/01/hunter-hd-actionadventure-classic-gets.html

I think it's open source, though I can't find a download link. These forum links are no help.

http://eab.abime.net/showthread.php?t=76593&page=6

**Comment by cxong** [comment]
links are dead unfortunately.
