### ISSUE TITLE
Add Rogue Legacy

### ISSUE THREAD

**Issue by kparal** [opengaming/osgameclones#2743]
Rogue Legacy developers published their source code to the game. It's not open-source, just source-available.

GitHub: https://github.com/flibitijibibo/RogueLegacy1/
Moby page for Rogue Legacy: https://www.mobygames.com/game/61110/rogue-legacy/
Announcement on X: https://x.com/CellarDoorGames/status/1846246914406195662
GamingOnLinux article: https://www.gamingonlinux.com/2024/10/rogue-legacy-1-source-code-released/

**Comment by alexpalade** [comment]
I can do it, I'll create a PR soon.
