### ISSUE TITLE
Add mystery-o-matic [similar to murdle/cluedo]

### ISSUE THREAD

**Issue by neuromancer** [opengaming/osgameclones#2788]
Not sure if it make sense to add since it is a web game that you can run locally but [the game is open-source](https://github.com/mystery-o-matic/mystery-o-matic.github.io). If you think it fits, let me know and I will create a PR.

```
name: mystery-o-matic
originals:
- murdle
- cluedo
type: similar
repo: 'https://github.com/mystery-o-matic/mystery-o-matic.github.io'
url: 'https://mystery-o-matic.com/'
development: active
content: open
langs:
- python
- html5
- solidity
licenses:
- AGPL3
added: '2024-11-23'
updated: '2024-11-23'
```

**Comment by cxong** [comment]
This doesn't come up often, but it seems we don't add clones of non-video games (e.g. board games) unless there is a video game version of that game and the game clones it. It's a weird distinction and there are exceptions (e.g. VASSAL). See https://github.com/opengaming/osgameclones/discussions/2789
