### ISSUE TITLE
Grit Engine

### ISSUE THREAD

**Issue by Mailaender** [opengaming/osgameclones#326]
http://www.gritengine.com/ has asset extraction tools for Grand Theft Auto: San Andreas. Not sure if this counts as clone or reimplementation. https://github.com/sparkprime/grit-engine/tree/master/gtasa

**Comment by wonea** [comment]
Fascinating, a bit like SCUMMVM but for open world games. Thanks for bringing this to our attention! I'm not entirely sure whether this go under GTA: San Andreas or all the other games listed on the Grit website; GTA series, Saints Row, Crysis, Fallout 3, Just Cause 2, Mafia 2, Burnout, etc.

Quite like this video:

https://www.youtube.com/watch?v=gARVzn3nBsQ

**Comment by cxong** [comment]
This would be a tool; need to implement this first: #71

**Comment by cxong** [comment]
This one is a bit tricky, because it also counts as a clone for the other games mentioned. For now I think we can just add it as an extraction tool for GTA:SA, since it doesn't seem like any of the other games are playable.
