### ISSUE TITLE
Build fails with pykwalify 1.6.0

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#429]
Latest version of pykwalify on travis is 1.6.0, but the project fails to build - example: https://travis-ci.org/piranha/osgameclones/builds/196755082

Previous successful builds used version 1.5.2

I've frozen the version to 1.5.2 for now

**Comment by nikuda** [comment]
Thanks @cxong. I'll have a look at this when I get a chance.

**Comment by nikuda** [comment]
Most likely related to https://github.com/Grokzen/pykwalify/issues/88

**Comment by cxong** [comment]
Linked issue is fixed and in 1.6.1 - although the release notes don't mention it. We can try it out.
