### ISSUE TITLE
Migrate CodePlex links

### ISSUE THREAD

**Issue by wonea** [opengaming/osgameclones#439]
CodePlex is slowly being shutdown

http://www.infoworld.com/article/3186701/open-source-tools/microsoft-to-shut-codeplex-open-source-project-site.html

We should keep track of the project(s) new homes.

**Comment by cxong** [comment]
https://github.com/piranha/osgameclones/search?utf8=%E2%9C%93&q=codeplex&type=
just two results, should be easy

**Comment by wonea** [comment]
MonoStrategy is possible duplicated. Finding out

https://github.com/albinmartin/monostrategy
https://github.com/albinmartin/monostrategy/issues/1

**Comment by cxong** [comment]
Both remaining projects look dead so no need to migrate them
