### ISSUE TITLE
Migrate Google Code links

### ISSUE THREAD

**Issue by wonea** [opengaming/osgameclones#440]
We still have quite a few games listed with Google Code links. Most of these have probably migrated somewhere else now.

The following folders have Google Code references.
![image](https://cloud.githubusercontent.com/assets/557192/24744698/d3a7d592-1aaa-11e7-8393-a3f963eb7c4e.png)

**Comment by cxong** [comment]
https://github.com/piranha/osgameclones/search?q=%22code.google%22&type=Code&utf8=%E2%9C%93
16 games

**Comment by Tom4hawk** [comment]
I've created pull request for OpenZelda, Twin-E, FoFiX, keeperfx.
What has left:
```
grep -rn 'code.google' .
./games/a.yaml:356:    url: https://code.google.com/p/artillery-duel-reloaded/
./games/b.yaml:80:    url: https://code.google.com/p/openbattlechess/
./games/b.yaml:122:    url: https://code.google.com/p/tzod/
./games/b.yaml:123:    repo: https://code.google.com/p/tzod/
./games/d.yaml:45:    url: https://code.google.com/p/darkreign2/
./games/e.yaml:61:    url: https://code.google.com/p/l-echo/
./games/f.yaml:95:    repo: https://code.google.com/archive/p/van-buren-project/
./games/f.yaml:197:    url: https://code.google.com/p/friking-shark/
./games/g.yaml:17:    url: https://code.google.com/p/geomwarsremake/
./games/g.yaml:188:    url: http://code.google.com/p/gta2net/
./games/g.yaml:189:    repo: http://code.google.com/p/gta2net/source/browse/trunk
./games/h.yaml:50:    repo: https://code.google.com/p/tombexcavator/source/browse/branches/v0/unsorted/hode-20090726
./games/l.yaml:71:    url: http://code.google.com/p/liero/
./games/l.yaml:74:    repo: http://code.google.com/p/liero/source/list
./games/r.yaml:79:    url: https://code.google.com/p/erampage/
./games/r.yaml:82:    repo: https://code.google.com/p/erampage/source/checkout
./games/s.yaml:154:    url: https://code.google.com/p/py1945game/
./games/s.yaml:669:    url: https://code.google.com/p/starshatter-open/
```
Those games didn't move out from Google Code (they were dead long before google code shutdown) so options are limited:
- most of them have unmodified forks created with migration tools - usually on GitHub
- create repo/s for dead projects (for historic preservation)
- remove them (most of them are in unusable state anyway)

**Comment by cxong** [comment]
If the source is still available, let's pick the most popular one. I think a couple of folks like @akien-mga did this at some point.
For the dead projects, I would rather they be removed.

**Comment by akien-mga** [comment]
I have some repos archived at https://github.com/LibreGamesArchive, from the top of my head at least l-echo, not sure about others.

**Comment by wonea** [comment]
@akien-mga I have archived Magic Carpet, would you like to include that in the Libre Games Archive?

https://github.com/wonea/magiccarpet

**Comment by akien-mga** [comment]
> I have archived Magic Carpet, would you like to include that in the Libre Games Archive?

Sure! Done.

BTW if some of you are also interested in dead FOSS games conservation, I'd gladly add more people with write access to the Libre Games Archive GitHub org.

**Comment by wonea** [comment]
@akien-mga That would be great. We recently lost a JavaFX Lemmings clone because the repo disappeared. Your the perfect person to have around! :-)

**Comment by cxong** [comment]
I've migrated all the ones I could find; added a danger warning if any PR contains a google code url just in case
