### ISSUE TITLE
Merge remake and clones

### ISSUE THREAD

**Issue by wonea** [opengaming/osgameclones#501]
Do you think we should merge remake and clones together? I would also like to list by date added or updated? @nikuda @cxong

**Comment by cxong** [comment]
I think so. It will also help games which have multiple inspirations.
The parent game should act more like a label. You can click on it to quickly filter games that are clones or inspired by it.

**Comment by wonea** [comment]
Okay, perhaps we should add a tag of 

type: [clone|remake] ?

**Comment by cxong** [comment]
I've split the games YAML files to originals and clones. Now games can be clones/remakes of multiple games.
This is only a backend change though, in the front end the entries are repeated.

**Comment by cxong** [comment]
Let's discuss how we'll present the list, now that the list is split and we can easily choose. We can show a list of originals plus their clones/remakes, or a list of all clones/remakes plus their original games. Or both?

For the combined originals list, if they have both clones and remakes, how should that be shown?

> Original game (RTS, Sci-Fi)
> - *CLONE* OpenGame (Playable, GPL, ...)
>    ...
>    ...
> - *REMAKE* SuperDuperGame (Not-Playable, Active, ...)
>    ...

?

**Comment by wonea** [comment]
I think we should show both. Users struggle to know what the difference is, so I don't we should try to forcibly educate them.

**Comment by cxong** [comment]
- [ ] Add verification for clones without remakes/clones
- [ ] Add verification for clones with non-existing original name

**Comment by nikuda** [comment]
> type: [clone|remake] ?

I like this.

**Comment by nikuda** [comment]
> I don't like the fact that we have two folders for clones and remakes now. Directory structure should go back to the simple listing of all, and the difference between remake/clones should be solved in the data structure/yaml.

To further the game itself is the top level, root node. By making the type the top node we introduce an odd way of thinking about it and there will be movements on the directory structure level. I.e. you change a type of game you move to it from one folder to the next and potentially delete/create new folders for new types. 

Everything except the game name is 'meta' information in terms of directory structure.

**Comment by cxong** [comment]
We don't have two folders for remakes and clones; we have folders for originals and clones.

**Comment by nikuda** [comment]
Same thing.

**Comment by cxong** [comment]
I'm not sure what you mean. The current split is between originals and their clones/remakes. This is to make the schemas flexible enough to have games that clone or remake multiple originals, and is being used by one game already.

`type` doesn't make sense here, unless you mean to add `type: clone | remake` for the clones/remakes?

The two have different schemas. Originals have a title that matches a wikipedia page, genres and themes. Clones have everything else, like repo, license and so on.

**Comment by nikuda** [comment]
Ah pardon, I thought it was going to be a clone/remakes split into folders. 

>This is to make the schemas flexible enough to have games that clone or remake multiple originals, and is being used by one game already.

Yes agree this is a good direction. I was thinking of doing this through the schema validation again but then we'd loose the `meta` information about the original game. This is better.

With how things are now I'd have two suggestions. Pull outs 'clones' back into games, so that that directory structure looks like this:

```
games/
  originals/
  a.yaml
  b.yaml
...
```

And the other thing is to use one key for referencing originals from games.  So use on key like `related` or `original`, instead of two `clones` and `remakes`. This new structure might look like:

```
repo: github.com/some/game
related:
  - name: Babaliba
    type: clone
```

**Comment by nikuda** [comment]
Also now that the originals are seperated we should think about changing this format

```
- name: [Abuse, Abuse (video game)]
```
to something like

```
- name: Abuse
  wikipedia: Abuse (video game)
```

**Comment by cxong** [comment]
I don't mind moving clones up a folder, just need to update all the references and links in the readmes though.

I disagree with moving clones/inspires into the originals. There are two use cases:
- Adding clone + original
- Adding clone

Having the clones/inspires in original YAML only makes the second use case harder, as you have to edit two files.

**Comment by nikuda** [comment]
> I disagree with moving clones/inspires into the originals.

Pardon I meant, only for the both originals and games to have the `meta` key, to hold information that connects them.

So the `meta` key for originals would remains the same, the `meta` key in games would hold `clones`, `relates`, `inspires`  etc, relationship keys which point back to originals.

**Comment by nikuda** [comment]
One remaining incomplete suggestion from #30 is to distinguish source ports from remakes and clones. Would be useful to know when a particular game is using original source which has been open sourced by the company. i.e. Doom.
