### ISSUE TITLE
Automatically check valid links

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#513]
I'm thinking of a way to automatically check all the links for the games so we can quickly find out if links go dead. Some questions though:

- How will this be checked? So far the only automatic process we have is Travis CI / the build script, so that's the first option, and to be run on every new commit
- Will this check be too slow? We have a few thousand links potentially (over 1000 games + clones, plus repo URLs, image/video URLs)
- Where do we see broken links? Should the main page actually indicate broken links? Or do we need some sort of dashboard? One idea I had was to present the results using a badge in the project readme (https://shields.io can do custom badges using a JSON data source)

**Comment by wonea** [comment]
I wouldn't want to immediately remove dead links although they should be highlighted. The Shields.io could be put to great use here.

Badge display: 1000 links 3 dead.

If all the checks takes 5 minutes I wouldn't be bothered.

**Comment by nikuda** [comment]
I've already done this for images. If you run `OSGC.validate()` it will go through all the image links and will find out if they're still reachable or slow, or too small or too big.

It could be extend to check the repo urls too I think. I was also considering adding a button and a UI for it so that any user can run it and get a report... This way it won't slow the build process.

**Comment by piranha** [comment]
Images could also be cached locally... I wonder though if it makes sense to put them in the repo (making it really big) or somewhere else (making this hard to manage).

**Comment by cxong** [comment]
better use a service like imgur, the images stay up for a long time and they handle all the traffic
github's own web hosting tends to be pretty slow

**Comment by piranha** [comment]
Well, after saving them to repo it could be server right from domain, but maybe imgur is really better - not sure about their policies, but if it's suitable, that's a good option!

**Comment by cxong** [comment]
There's already a utility available: [awesome_bot](https://github.com/dkhamsing/awesome_bot)
This can be run on the `games/` folder.
There are lots of broken links already; need to remove or fix them, and then include awesome_bot in the build.

**Comment by cxong** [comment]
The checking can be done on PRs, and only on files changed. This won't slow down the build and will help gradually fix the existing broken links.

**Comment by nikuda** [comment]
> only on files changed

This is a good idea, might be ok with this. ☺️

**Comment by pehsa** [comment]
I got the URLs from the live page and runned one validator on them. I attached the result. Theres around 100 URLs are invalid. (I don't have information for the FTP, GIT and SVN URLs.)

[export.xlsx](https://github.com/opengaming/osgameclones/files/3491356/export.xlsx)

**Comment by cxong** [comment]
Images have been removed from the main page, and also since checking links is too slow or can't be done easily via CI, it should be moved to a script that we run occasionally.

**Comment by cxong** [comment]
```
https://www.ya2.it/_images/yorg_0_11_a.jpg returned 404 (Yorg)
https://raw.githubusercontent.com/csinkers/ualbion/master/data/Screenshots/1_FirstLevel.png returned 404 (UAlbion)
https://raw.githubusercontent.com/csinkers/ualbion/master/data/Screenshots/2_3DWorld.png returned 404 (UAlbion)
https://raw.githubusercontent.com/csinkers/ualbion/master/data/Screenshots/3_Outdoors.png returned 404 (UAlbion)
https://raw.githubusercontent.com/csinkers/ualbion/master/data/Screenshots/4_Inventory.png returned 404 (UAlbion)
https://raw.githubusercontent.com/csinkers/ualbion/master/data/Screenshots/5_MainMenu.png returned 404 (UAlbion)
https://usplay.net/assets/img/devices_usplay_mic_in_phone.png returned 404 (UltraStar Play)
https://usplay.net/assets/img/screenshots/singing-resized.png returned 404 (UltraStar Play)
https://usplay.net/assets/img/screenshots/results-resized.png returned 404 (UltraStar Play)
https://github.com/krzys-h/UndertaleModTool/raw/master/screenshot.png returned 404 (UndertaleModTool)
https://terasology.org/img/ss_1.jpg returned 404 (Terasology)
https://terasology.org/img/ss_2.jpg returned 404 (Terasology)
https://terasology.org/img/ss_3.jpg returned 404 (Terasology)
https://terasology.org/img/ss_4.jpg returned 404 (Terasology)
https://projecttussle.com/ returned 403 (TUSSLE)
https://raw.githubusercontent.com/ian-wigley/Xenon/master/Xenon/Xenon.jpg returned 404 (TypeScript Xenon)
https://mafiamods.com/wp-content/uploads/cmdm/165255/1580170866_132-1579280887-1378041516.png returned 403 (Mafia II: Toolkit)
https://mafiamods.com/wp-content/uploads/cmdm/165255/1580170881_132-1579280933-563824247.png returned 403 (Mafia II: Toolkit)
https://mafiamods.com/wp-content/uploads/cmdm/165255/1580170906_132-1579281675-1092920346.png returned 403 (Mafia II: Toolkit)
https://megaglest.org/uploads/images/Gallery/Screenshots/more_screens10.jpg returned 404 (MegaGlest)
https://megaglest.org/uploads/images/Gallery/Screenshots/screen44.jpg returned 404 (MegaGlest)
https://axiodl.com/images/hecl_hu25398d5c0d2da88c4a5221db09696c79_1724775_0x480_resize_bg292a2d_box_2.png returned 404 (Metaforce)
https://axiodl.com/images/pwe_hu7c7bec678fa5eef23b41aaa434dfa04c_1742668_0x480_resize_bg292a2d_box_2.png returned 404 (Metaforce)
https://mindustrygame.github.io/images/1.png returned 404 (Mindustry)
https://mindustrygame.github.io/images/2.png returned 404 (Mindustry)
https://mindustrygame.github.io/images/3.png returned 404 (Mindustry)
https://github.com/Javanaise/mrboom-libretro/raw/master/tests/screenshots/mrboom-0.gif returned 404 (Mr.Boom)
https://github.com/Javanaise/mrboom-libretro/raw/master/tests/screenshots/mrboom-1.gif returned 404 (Mr.Boom)
https://github.com/Javanaise/mrboom-libretro/raw/master/tests/screenshots/mrboom-2.gif returned 404 (Mr.Boom)
https://github.com/Javanaise/mrboom-libretro/raw/master/tests/screenshots/mrboom-3.gif returned 404 (Mr.Boom)
https://github.com/Javanaise/mrboom-libretro/raw/master/tests/screenshots/mrboom-4.gif returned 404 (Mr.Boom)
https://github.com/Javanaise/mrboom-libretro/raw/master/tests/screenshots/mrboom-5.gif returned 404 (Mr.Boom)
https://github.com/Javanaise/mrboom-libretro/raw/master/tests/screenshots/mrboom-6.gif returned 404 (Mr.Boom)
https://github.com/Javanaise/mrboom-libretro/raw/master/tests/screenshots/mrboom-7.gif returned 404 (Mr.Boom)
```
