### ISSUE TITLE
Repo type icons

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#514]
I would like some indicator for the type of repo, like an icon for example:

![screen shot 2017-11-02 at 11 19 57 pm](https://user-images.githubusercontent.com/1083215/32325784-7ae57282-c024-11e7-9a2e-95dccb9b4c01.png)

I prefer github because it's easy to use for me, but others might prefer providers like bitbucket or gitlab for various reasons. Also I think it'll be great to see at a glance whether the repo link is actually pointing to a .zip or .tar.gz archive.

So far most repos are github, but we also have sourceforge, bitbucket, launchpad, google code, savannah, and zip/tgz blobs.

The icons may need to have dark versions.

**Comment by wonea** [comment]
Great idea.
