### ISSUE TITLE
New games

### ISSUE THREAD

**Issue by wonea** [opengaming/osgameclones#523]
https://en.wikipedia.org/wiki/The_Oregon_Trail_(video_game)
https://github.com/TheRedSpy15/The-Trail

https://en.wikipedia.org/wiki/Disney%27s_Aladdin_(Virgin_Games_video_game)
https://github.com/phanletrunghieu/Aladdin_DirectX

**Comment by GGLapkizzz** [comment]
I wonder if I should post a new game here, or submit a new issue?
http://www.braingames.getput.com/nether/
https://en.wikipedia.org/wiki/Nether_Earth

**Comment by cxong** [comment]
ElevatorAction is 404

**Comment by cxong** [comment]
The-Trail has been archived

**Comment by cxong** [comment]
Space-Harrier-Clone already added

**Comment by cxong** [comment]
nether earth doesn't load for me. Is there an online repo for it?
