### ISSUE TITLE
New GitHub organisation & project name?

### ISSUE THREAD

**Issue by nikuda** [opengaming/osgameclones#527]
Per https://github.com/piranha/osgameclones/issues/398#issuecomment-266744746

> @piranha: Do you think we can assemble committee which will carry the project forward given much bigger scope?

It would be useful to create new repos that relate to the project. For example this current repository could become the data repository and a new repository can be made to drive a v2 of the UI. UI v2 would consume this repos data.

**Comment by piranha** [comment]
Sure! I've been looking at all the activity around the project and that seems like a good idea. This organization could also serve as archive/copy for game sources, for example, in case original site is down or something. What's a better name for an organization, `osgc` or `osgameclones`?

**Comment by nikuda** [comment]
'Open Source' in name is problematic because some of the game are not licensed in a clear way (therefore not open sourced) and others are explicitly not open sourced.

'Clones' in the name is also not very useful anymore because most of the focus so far has been on remakes.

I'd suggest we just come up with a new name, that just has 'games' in it. For example 'Games Vault' or something similarly abstract.

**Comment by cxong** [comment]
I suggest "Open Game Remakes", or something similar.

- Just using "Open" to avoid clearly defined terms like "open source". The goal is still to have the source code in a free/open license, although we are lenient in accepting games with no license, as we assume those projects should be open source once the licensing is clarified. "Open" also relates to similar terms like "open access" and "open content".
- "Remakes" to avoid negative connotations of "clone"

**Comment by nikuda** [comment]
> "Open Game Remakes"

I think this is a good gradual progression that fixes the current problems with the name. My concern though is that the name might again become a constraint in the near future. There were already talks about including games that are not clones or remakes in #406. Something that might be worth doing in the future.

I think we should have an 'About' document were we specify the scope of the project, but that scope shouldn't be in the name because it becomes less flexible to changes/growth.

The core thing that the project does is listing (archiving) sources of game source code that is found publicly on the internet. So at core it's an archiving effort and that won't change for a long time if ever. The types of game sources that are archived might change but that core functionality won't, so it's safer to make the name around it - rather than around a particular type of game.

**Comment by nikuda** [comment]
> This organization could also serve as archive/copy for game sources

I really like this idea. It shouldn't be hard to function as a mirror / backup of repos that are not already on GitHub.

**Comment by piranha** [comment]
If "good old games" weren't already taken, I'd say that's a good name. :)) "Open Game Remakes" - not sure this describes project well enough or catches attention... I don't have better suggestions out of mind though, and that one is not bad. :)

**Comment by vsolovyov** [comment]
> This organization could also serve as archive/copy for game sources

Original creator of osgc here. I also think that this is a wonderful idea. It's not

Also, there is nothing special about the current name. I knew about a few open-source game recreations (particularly OpenTTD, VCMI and CorsixTH, looking at the first commit), wanted to find if there were more games like this and typed "open source game clones" into google. There wasn't anything good, so I registered the domain that matched my search query and created that first version :)

As I remember, queries like "open source game clones" and very similar were the most common sources of traffic, that's how a lot of people find this project. To this day organic search is like 70% of the traffic. Strangely, I couldn't find query report in Google Analytics right now. Nevertheless, if you will choose to rename the project, don't forget to include all these "open source", "game clones", "game remakes", etc in proper places for SEO purposes.

**Comment by nikuda** [comment]
>  I knew about a few open-source game recreations (particularly OpenTTD, VCMI and CorsixTH

OpenTTD and CorsixTH are what got me interested in this as well.

> As I remember, queries like "open source game clones" and very similar were the most common sources of traffic, that's how a lot of people find this project. To this day organic search is like 70% of the traffic.

The existing domain could still stay active and drive the traffic to whatever the new domain is. 👍

**Comment by nikuda** [comment]
If we're going with literal names how about 'Games Source Archive' or 'Games Code Archive'

Typing those in google returns

* https://en.wikipedia.org/wiki/List_of_commercial_video_games_with_available_source_code
* https://archive.org/details/gamesourcecode

Both relevant to OSGC.

**Comment by piranha** [comment]
Hey! So I've decided that it's better to take action and if we want to rename organization that's still possible. :-) We're at @opengaming now :)

**Comment by wonea** [comment]
Great! I like it! Your giving me a nudge to find some new games!

**Comment by piranha** [comment]
Also there is a place to archive all this stuff around the internet! :-)
