### ISSUE TITLE
Deploy new website after each commit

### ISSUE THREAD

**Issue by kparal** [opengaming/osgameclones#581]
Currently if a new game gets committed (pull request merged, etc), the https://osgameclones.com/ website is not updated. That clearly happens manually, and not so frequently. That is not ideal user experience - people can't easily immediately check that the new item is rendered correctly, and there's a possibility of effort duplication (somebody else submitting the same game because the PR is merged but web not deployed yet).

It shouldn't be difficult to set up an automated system that deploys new web after each change (either as a commit hook, or at least periodically fetching the sources and rebuilding every hour or so). Please consider this, thank you.

**Comment by cxong** [comment]
Interesting; this used to get built by Travis CI, it disappeared at some point but I didn't look into it. I wonder if it was a side effect of moving to the opengaming organization? Will need @piranha 's help here.

**Comment by piranha** [comment]
Damn! :o I really forgot about configuring travis after we've moved organizations!

**Comment by piranha** [comment]
Seems to be working now? Let's check on next merged pull request. :-)

**Comment by nikuda** [comment]
Travis-CI integration seems to have stopped working in PRs as well. There's a newish `Checks` tab in the PR section with a Travis-CI app that might be worth enabling as well. @piranha

**Comment by piranha** [comment]
Are you sure? :) Last closed pull request was 8 days ago and I fixed travis ci only 3 days ago... Settings in travis-ci look okay, so should be working!

**Comment by nikuda** [comment]
My bad. This seems right 👍

**Comment by nikuda** [comment]
All working.
