### ISSUE TITLE
Question about asdf

### ISSUE THREAD

**Issue by tzizi** [opengaming/osgameclones#589]
I'm currently working on an implementation for #520, but I found asdf (https://github.com/TimPietrusky/asdf) in the list of remakes that don't have an original game associated.

Does this count as an open-source game clone? It seems more like an electronic toy than a computer game to me. If it does, what should it be classified under, Arcade? Also, wouldn't this be considered as a clone, rather than a remake?

**Comment by nikuda** [comment]
Yes it's a clone by our categorisation. Arcade seems like the most appropriate genre.

I'd add Simon https://en.wikipedia.org/wiki/Simon_(game) to the originals list and then link it to asdf.
