### ISSUE TITLE
Split alternate names into separate games

### ISSUE THREAD

**Issue by tzizi** [opengaming/osgameclones#600]
While trying to split up the name section in original games in a fashion similar to [this comment](https://github.com/opengaming/osgameclones/issues/501#issuecomment-348024836), I came across alternate names, which made things a bit complicated.

It seems most of the time it's used as a way to batch up similar games, for example with Neverwinter Nights.

However, if someone were to make another remake of Neverwinter Nights (or any of the other related games), they'd have to split up the games, unless they supported every game xoreos supported as well.

One way to go about this is to split them into separate games, but add a `related` property, that would batch them up as they were previously, however, this doesn't really fix the issue.

Another option would be simply to make the remakes specify all the games they remake. I personally prefer this option, as if #596 is implemented, it would allow specifying an alternate status for every game it supports.

While I understand the appeal of batching up, I personally believe it makes things a little bit less organized. However, if it's important, we could also batch up games that only one remake implements (or more than one, as long as they remake the exact same games). This would probably take more work though.

**Comment by cxong** [comment]
I think this is a legacy of when games couldn't remake multiple games. Moving forward we should just split everything.

**Comment by tzizi** [comment]
Alright, I'll do it that way then :)
