### ISSUE TITLE
Sort by remake/clone

### ISSUE THREAD

**Issue by tzizi** [opengaming/osgameclones#601]
The idea here is to create an alternate version of the page, sorting by remakes/clones instead of by original game.

The reasoning for this is that the batching described in #600 seems to be a sort of hack for this. If an alternate page was created, then one could simply look at the list of original games each clone/remake bases itself on. It would then allow the issue in #600 to be fixed cleanly, as the functionality would be present in this page.

**Comment by cxong** [comment]
I'm not sure if this is worth the trouble. The current website supports the user story of "finding open source games similar to X". Going the other way isn't something that seems useful to me.

The issues in #600 can be fixed without creating the alternate version.

**Comment by tzizi** [comment]
Yeah I agree, I started to doubt if this was a good idea a few hours aften opening it.
