### ISSUE TITLE
Fallout 3 Van Buren link is dead

### ISSUE THREAD

**Issue by tntmod54321** [opengaming/osgameclones#645]
The link for the Fallout 3 Van Buren remake is dead (http://vanburenproject.blogspot.com/) but the indieDB page is still up (https://www.indiedb.com/games/van-buren-project)
I also noticed that the page said specifically remakes of games and didn't mention plain open source games, but I saw cataclysm dark days ahead in the list, which as far as I know isn't a remake, so I thought I'd mention an underappreciated game that I played when I was a kid Warfare Incorporated, with the source code released as "Hostile Takeover" (https://github.com/spiffcode/hostile-takeover)

**Comment by tntmod54321** [comment]
Another Minecraft clone (https://github.com/Hopson97/MineCraft-One-Week-Challenge)

**Comment by cxong** [comment]
Van buren has been updated.
I'm not familiar with cataclysm DDA but we don't really accept original open source games in the list; they need to at least be inspired by some other game (which itself could be open source, though).
