### ISSUE TITLE
OpenNFS originals?

### ISSUE THREAD

**Issue by pehsa** [opengaming/osgameclones#684]
I have a problem with the OpenNFS project (https://github.com/AmrikSadhra/OpenNFS).

They want to recreate the classic NFS games engine (1-6). 

In the originals we have NFS and NFS II SE. Should I add all games to the originals or add as group?

**Comment by cxong** [comment]
I'm not familiar with the NFS games series, but if they are substantially similar (e.g. same engine used for multiple games) then they can be added as a single original game
Then OpenNFS can clone NFS, NFS II SE and whatever other NFS games there are

**Comment by pehsa** [comment]
I added OpenNFS. The only original I added is NFS III, because that implementation almost done.
