### ISSUE TITLE
Sorting YAMLs?

### ISSUE THREAD

**Issue by pehsa** [opengaming/osgameclones#691]
Is there any way to sorting YAML files?

I try adding new games according to scheme files, but I always check the tags order when adding a new game. The other game entries not helping because those not following the scheme order.

**Comment by cxong** [comment]
The files are usually hand edited so there's no way to prevent them from becoming unsorted over time again
I was thinking of moving towards assisted data entry, but that's a bit further off

**Comment by Trilarion** [comment]
I could write a small Python script that sorts the YAMLs. It could then be run occasionally by a maintainer before a commit. That way regular committers would not need to worry about the sorting until some assisted data entry exists.

**Comment by Trilarion** [comment]
I wrote a small Python script to perform the sorting and it looks okay locally (mostly resorting of the games, some indentation changes). The script is hosted at https://gist.github.com/Trilarion/34ebcdf9d50323ab47f75382318bf793

However, in the pull request (https://github.com/opengaming/osgameclones/pull/887) dangerJS crashed.
