### ISSUE TITLE
Tribal Hero issues

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#698]
![image](https://user-images.githubusercontent.com/1083215/55296063-66373b00-5460-11e9-97d8-49ddb5f29d08.png)

- Tribal Hero is unrelated to Tricky Towers
- It used to have a clone, which was removed later (should not render originals with no clones)
- Tribal Hero wikipedia page broken; look for a replacement or remove altogether

**Comment by pehsa** [comment]
Not just Tribal Hero has this problem:

- Floor13 next to Flying Shark
- The Goonies next to Gorillas
- The Lord of the Rings Volume 1 next to Lose Your Marbles
- The Maze of Galious next to MechCommander 2
- Nether Earth next to Neverwinter Nights
- Quadnet next to Quake
- RoadFighter next to Robotfindkitten
- Scramble next to Sea Dragon
- Starfox 64 next to Star Raiders
