### ISSUE TITLE
Thrive

### ISSUE THREAD

**Issue by PaulElectron** [opengaming/osgameclones#705]
https://github.com/Revolutionary-Games/Thrive

**Comment by cxong** [comment]
Is this a clone of any game? I can't tell, and the game website says it might not be:

>Thrive takes many games as inspiration, from roguelikes to grand strategy games, but we plan on walking our own path with many game mechanics. Don’t expect a clone.

**Comment by pehsa** [comment]
We can add Thrive as Spore clone. In the FAQ:
"While Thrive was originally widely inspired by Spore’s intended concept, we aim to portray a creature’s evolution in a fun and interesting way while remaining scientifically accurate."
