### ISSUE TITLE
Maybe add links to tools?

### ISSUE THREAD

**Issue by keplerbr** [opengaming/osgameclones#71]
It would be interesting to add a section of modding tools and studies of old games.

<b>Example</b>
Camoto: http://www.shikadi.net/camoto/
Moddingwiki: http://www.shikadi.net/moddingwiki/Main_Page

**Comment by cxong** [comment]
We don't have to change the layout of the site. Tools can be added as another type of "clone" (`remake`, `clone`, the proposed `port` #533, and now `tool`)

We could add a new filter to filter out tools by default. But once tools are shown, they'll just show up in the same big list.

Other questions:

- What types of tools will there be, and what name(s) do we use? Tool? Modding? Resource? Let's come up with a list.
- Do we need a different schema? What different fields would it have? For tools maybe we can include tags for what it can edit, like levels, (extract) assets, debug/cheats... For websites that document file formats, maybe we don't need them to have an open source license.
