### ISSUE TITLE
Fix GPL games

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#742]
Usually games use GPL2 or GPL3. There is a GPL version 1 but it is very rare; most games currently listed as GPL are most likely misclassified.

- Check all the games currently listed as GPL, change as necessary: https://github.com/opengaming/osgameclones/search?q=GPL&unscoped_q=GPL
- Add a Danger check if the license is GPL

**Comment by tzizi** [comment]
Maybe `GPL` could also be renamed to `GPL1` to make it clearer to both users of the site, and people creating pull requests?

**Comment by cxong** [comment]
Similar thing with LGPL actually - there is no version 1, so it should be removed altogether

**Comment by cxong** [comment]
Hopefully having it called `GPL1` will prevent people from using it by mistake
