### ISSUE TITLE
Combine Transport Tycoon / Transport Tycoon Deluxe?

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#747]

**Comment by wonea** [comment]
After reading through the Wikipedia article I don't think there would be many people who would be interested in the non-deluxe version.

![image](https://user-images.githubusercontent.com/557192/58085314-69bf8680-7bb4-11e9-9241-df26f876f057.png)

**Comment by pehsa** [comment]
There are no open source project which want to recreate the original Transport Tycoon. There are just minor changes (except the new enviroments) between the original and the Deluxe edition.

So the two can be combined to one entry with alt name, or just having the Deluxe edition.
