### ISSUE TITLE
Sanitarium

### ISSUE THREAD

**Issue by zafos** [opengaming/osgameclones#768]
https://code.google.com/archive/p/asylumengine/

**Comment by cxong** [comment]
I think it's better to link to the scummvm feature branch here https://github.com/alexbevi/scummvm

**Comment by zafos** [comment]
You're absolutely right, I only put the deprecated URL as it provides a bit more information on the actual project.

**Comment by hansejo** [comment]
Issue can be closed. The game is going to be supported in the upcoming ScummVM release: 

https://wiki.scummvm.org/index.php/Sanitarium
