### ISSUE TITLE
Warn on unknown languages

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#786]
We should include a list of known programming languages, and if unknown ones are added, warn in the pull request.

This is because there could always be new programming languages, but we'd also like to check if people accidentally misspell a known one (like `Javascript` instead of `JavaScript`).

Or if languages not typically relevant for games developers are added, like HTML or CSS.

**Comment by Trilarion** [comment]
As a first step, I iterated over all entries and create the set of existing programming language names. It could be the template of known languages.

['ActionScript', 'Ada', 'AngelScript', 'Assembly', 'Blitz BASIC', 'C', 'C#', 'C++', 'CoffeeScript', 'CSS', 'D', 'Delphi', 'Elm', 'F#', 'GDScript', 'GLSL', 'Go', 'Haskell', 'Haxe', 'HLSL', 'HTML', 'HTML5', 'Java', 'Javascript', 'JavaScript', 'Lisp', 'Lua', 'Object Pascal', 'Objective-C', 'ooc', 'Pascal', 'Perl', 'PHP', 'Python', 'QBasic', 'QuakeC', 'QuickBASIC', 'Ruby', 'Rust', 'Scala', 'Swift', 'TorqueScript', 'TypeScript', 'Typescript', 'Visual FoxPro']

Already now: Javascript -> JavaScript and Typescript -> TypeScript.

HTML, HTML5 remove?

What is QuakeC?

**Comment by OvermindDL1** [comment]
> QuakeC

It's a scripting language built on and part of the stock quake engine.

I.E. Any game using that is built on the quake engine using the scripting language QuakeC.

**Comment by Trilarion** [comment]
Thanks. I wonder if HTML, HTML5, HLSL, GLSL should be included or not?

Github also displays them, but they seem to be more like some kind of markup than a real programming language.

See also https://stackoverflow.com/questions/24569439/are-gpu-shaders-turing-complete https://stackoverflow.com/questions/14512218/is-html5-a-programming-language

**Comment by OvermindDL1** [comment]
HTML/HTML5 could very well be a single thing, and games could be made in it, and it is distinct from javascript and wasm (both of which are distinct from each other).

GLSL/HLSL/SPIRV/etc are all the same backend of different languages, could be included together as 'Shaders', but honestly I don't see how a game would really be made in them unless it's showing off something very simple.  ^.^

**Comment by Trilarion** [comment]
I will start working on implementing the feature.

Meanwhile a few more voices regarding the inclusion/exclusion of HTML/HTML5/GLSL/HLSL in the list of known languages would be good.

**Comment by cxong** [comment]
Please remove CSS too

**Comment by OvermindDL1** [comment]
I have seen the game of life made in CSS, but beyond that I don't see how it could be a game language, lol.

**Comment by Trilarion** [comment]
See PR #900
