### ISSUE TITLE
RTS/TBS genres?

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#804]
In the originals schema, we have the following genres:

- RTS
- Real-Time Tactics
- TBS
- Turn-Based Tactics

And in the subgenres:

- Turn-Based Strategy
- Turn-Based Tactics

There's two problems with this:

- Some genres are repeated, but with different names - e.g. "TBS" and "Turn-Based Strategy"
- These similar classifications are split between genres and subgenres

I suggest consolidating them, all within genres, and with similar naming styles - e.g.

- RTS
- RTT
- TBS
- TBT

**Comment by nikuda** [comment]
Are those terms (outside of RTS) used by anyone? I've never seen them used outside people talking about it here. If that approach is taken those tags definitely need a tooltip disambiguation of the term. 

Another approach would be seperate _time_ from (more general) _genre_.

* Real-time
* Turn-based
* Tactics
* Strategy

For this to work the tagging system would have to change to allow multiple tags to be selected at once (which would be useful for other things too). If it's not clear with this system to get RTTs, you'd select `Real-time` + `Tactics` tags.

Same thing to apply to _perspective_ + _genre_. i.e. `First-person` + `Shooter` to get FPS'.

**Comment by nikuda** [comment]
I think the original intention with `Turn-Based Strategy` and `Turn-Based Tactics` is for them to be sub-genres of 'Strategy' and 'Tactics' respectively. This clearly didn't work or the schema was modified to allow the more ad-hoc entries.

Acronym's entries (RTS/TBS) were smuggled in by a particularly insistent contributor. 

Still, RTS/TBS could be used as codes for those genres in data files, but I'm generally against them being used in the UI, at least without some disambiguation of what they mean.

**Comment by cxong** [comment]
Let's use the full names then to avoid confusion. However we can continue discussion of splitting genres to another issue.
