### ISSUE TITLE
Show different multiplayer tags

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#813]
We added different types of multiplayer tags in #522 but they only show up as a single `Multiplayer` tag in the website. It would be great if the different types can be shown.

**Comment by pehsa** [comment]
I think we need to place the multiplayer tags into a new line, like this:

![Multitags](https://user-images.githubusercontent.com/30371056/62622263-36bca180-b91e-11e9-8e77-a35e07bb1118.jpg)

If one game has 2-3 or more multiplayer tags, this design will be more easy to read.

**Comment by cxong** [comment]
What about prefixing the tag type as in #831?

**Comment by pehsa** [comment]
The problem with the prefixed tags is if a game has many tags than we will have 3 or more line tags:
![kép](https://user-images.githubusercontent.com/30371056/63948692-62dcc580-ca79-11e9-942a-bcfe990ce042.png)

I think we need to find the way to group the tags. Like: "multiplayer: Co-op, Online, LAN" Thats one tag. Similar solution to every tag type which array type (license, framework, lang). The only problem, I don't know now how we able to filter them.

**Comment by cxong** [comment]
Good observation; I think if we want to minimise the number of lines, we could have the tag prefixes outside the tag buttons, and one per type of tag

**Comment by pehsa** [comment]
Closable #877
