### ISSUE TITLE
Prefix tag type

### ISSUE THREAD

**Issue by tzizi** [opengaming/osgameclones#831]
Instead of having `commercial`, we could have something like `content:commercial`. Although it would lengthen the names of the tags, I think it would also make it much clearer what the tags are for.

**Comment by cxong** [comment]
let's preview what it looks like; it might affect the layout

**Comment by cxong** [comment]
![image](https://user-images.githubusercontent.com/1083215/61679682-5ebadb00-ad4a-11e9-8d61-0d89ff37f6ff.png)

**Comment by pehsa** [comment]
Closable #877
