### ISSUE TITLE
Some home page URLs are offline by now, replace with webarchive links?

### ISSUE THREAD

**Issue by Trilarion** [opengaming/osgameclones#856]
Some of the game clones have no home page anymore. The existing urls either give an error or return unrelated content. 

For example: https://www.civone.org/, http://commandojs.org/, http://freerct.org/, http://naev.org/, http://openzelda.nfshost.com/, http://apocalypse.rulez.org/pangzero, http://www.ryzomcore.org/, http://www.sumwars.org/

The projects are mostly quite old and inactive. It would be possible to find archived versions of these sites in the webarchive.

What should be done about it?

- remove the url field for these game entries?
- replace these links with webarchived versions (should they be marked in a special way then)?
- something else?

**Comment by pehsa** [comment]
I think we need to remove the URLs. The Repos are up and they provide enough information. No need to look for the webarchive.

No problem until the repo is available. Now we have only one game which url and "repo" are unavailable. 3D Deathchase. The url and the repo are webarchive links.

**Comment by Trilarion** [comment]
Could be done like this, but a retrieved site from the archive can bring a lot of information about the project (how much activity there once was, was people expected from it, …). This is what you would lose by completely removing the links.

**Comment by Trilarion** [comment]
I made a PR in https://github.com/opengaming/osgameclones/pull/890 about removing them
