### ISSUE TITLE
Danger warn if no images or videos

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#865]
Images and videos are really helpful, it would be great for Danger to note when there's a game being added/updated that doesn't have images

**Comment by Trilarion** [comment]
Maybe there should also be a automatically compiled list of entries without images or video in the repo. That way people could start searching for image/videos systematically and add them. If the list existed, it could be a good first issue to check and search for media content for games from that list.

**Comment by cxong** [comment]
No need; that should be obvious from looking at the website - it will be the games without the expando arrow
