### ISSUE TITLE
Suggestion Talk about your project

### ISSUE THREAD

**Issue by Astuceman** [opengaming/osgameclones#873]
Your idea is really great and you should open an issue in each repo of each game. (saying there a list of open source games)
You will get more view, help and make some dev happy 😄.

You can use Alternativeto.net. Their database is strong for software but weak for games.

**Comment by cxong** [comment]
Thanks for the reminder. I've thought that we should let authors know whenever their projects are added here; I've added a bot message as a reminder, you can see an example here: https://github.com/opengaming/osgameclones/pull/874#issuecomment-526812988
I don't think we need to open an issue as that's disruptive. We can @ mention them though and they'll get a notification on github.

**Comment by Astuceman** [comment]
that's an good idea. If you think that's better, go on.
I close this issue.
