### ISSUE TITLE
.tag-group broken in #877

### ISSUE THREAD

**Issue by handsomematt** [opengaming/osgameclones#879]
![image](https://user-images.githubusercontent.com/1388267/64136648-0ec04100-cdeb-11e9-96bf-5dfcc2784324.png)

tags in header are now broken since #877 the PR was marked as WIP, don't think it was ready to merge.

**Comment by pehsa** [comment]
Yeah, I marked WIP because I want to redesign, and didn't test everything. I will trying to fix the header today

**Comment by pehsa** [comment]
I didn't check and we already have a tag-group class and my new class cause the conflict. I renamed my class, and add a new macro to the tags to separate the two tag group generating.

**Comment by handsomematt** [comment]
#882 fixed this
