### ISSUE TITLE
Combine Doom and Doom II

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#895]
The two games share a common engine so clones tend to clone both
This should reduce some duplication on the website

**Comment by cxong** [comment]
Maybe we can add Heretic and Hexen too? I don't have a strong opinion on those two

**Comment by kazgaroth011** [comment]
I agree. Also my suggestion for combining:
- Icewind dale & Planescape torment with Baldur's gate series (it's basically the same engine)
- XCom Terror from the deep + XCom UFO Defense + UFO Enemy unknown
- Put XCom apocalypse in its own section with just OpenApoc listed
