### ISSUE TITLE
Unix ASCII games has security warning

### ISSUE THREAD

**Issue by wonea** [opengaming/osgameclones#896]
Link at the top of our main page has a security warning

![image](https://user-images.githubusercontent.com/557192/65229853-d8f6aa00-dac4-11e9-817a-7eeb5e212a5c.png)

Displays the following error

![image](https://user-images.githubusercontent.com/557192/65229929-f3308800-dac4-11e9-86ce-16677d4d44a5.png)

**Comment by cxong** [comment]
hmm I wonder if this is a good chance to revise the intro text
I was thinking we should add https://trilarion.github.io/opensourcegames/ and https://github.com/leereilly/games for example.

**Comment by wonea** [comment]
The ASCII games was a sister site, I don't much about it. Yes, I think we should add those links you mentioned.

**Comment by OvermindDL1** [comment]
When you bypass HSTS, all that site does not is redirect you to https://github.com/ligurio/awesome-ttygames so perhaps it is better to just link to that?

**Comment by cxong** [comment]
@OvermindDL1 good idea; unless they fix their site, that's a good workaround

Another idea: add a count of clones + games on the page
