### ISSUE TITLE
Warn on other unusual field content

### ISSUE THREAD

**Issue by Trilarion** [opengaming/osgameclones#903]
Analogously to #786 (which can be closed now) we could also check and warn for other known field contents. For the various proposals please see the posts below. If there is a consensus, I could make a PR for it.

**Comment by Trilarion** [comment]
The development field has the following content (number of occurrences in parentheses)

halted(326), active(325), sporadic(124), complete(32), very active(6)

Therefore we could use these 5 words as valid development attributes and check for them.

**Comment by Trilarion** [comment]
The type field has the following content:

remake(670), clone(165), similar(10), tool(4)

We could use these 4 words as valid type attributes and check for them.

**Comment by Trilarion** [comment]
The multiplayer field has the following content:

Online(28), LAN(16), Competitive(9), Split-screen(7), Local(3), Hotseat(3), Co-op(2)

We could use these 7 words as valid multiplayer field attributes.

**Comment by Trilarion** [comment]
The content field has the following content:

commercial(95), open(59), free(27), swappable(5)

We could use them as valid content attributes.

**Comment by Trilarion** [comment]
The status field has the following content:

playable(263), semi-playable(31), unplayable(30)

We could use them as valid status field attributes.

**Comment by Trilarion** [comment]
Regarding the multiplayer field, should it maybe also be converted to start with lowercase (except for LAN) to be more in line with the other field contents?

**Comment by Trilarion** [comment]
Additionally, fields license and framework could be checked.

**Comment by cxong** [comment]
these are enforced by the schema check already and will fail the build
danger is only used for warnings, where there is uncertainty whether a strict schema is required
except for framework, we could do that.

**Comment by Trilarion** [comment]
Frameworks are quite a lot:

SDL(43), SDL2(41), OpenGL(13), Unity(10), SFML(9), WebGL(9), OGRE(7), Allegro(7), Phaser(5), DIV Games Studio(5), Qt(5), LÖVE(4), LibGDX(4), QB64(3), pygame(3), ncurses(3), MonoGame(3), XNA(3), three.js(2), Irrlicht(2), Panda3D(2), React(2), Redux(2), QT5(2), SDL2, boost (partial)(2), Godot(2), Pygame(2), Kylix(2), Allegro4(1), Sea3D(1), EntityX(1), Box2D(1), MelonJS(1), melonJS(1), JQuery(1), Gradle(1), EnTT(1), GameMaker Studio(1), BackBone.js(1), Source SDK(1), Flash(1), GTK+(1), ZLIB(1), QT(1), Cube 2 Engine(1), Mono(1), Duality(1), HTML canvas(1), Irrlict(1), libgdx(1), Rx.js(1), Three.js(1), Tween.js(1), libGDX(1), nya-engine(1), Laravel(1), JMonkeyEngine(1), Bullet3(1), phaser(1), Qt5(1), .NET Core(1), Love3D(1), Monogame(1), Construct2(1), Construct(1), JavaFX(1), PandaJS(1), Spring RTS Engine(1), VDrift Engine(1), pixi.js(1), SWT(1), jQuery(1), PyGame(1), Torque 3D(1), Inform(1), NeoAxis Engine(1), Gobot(1), Netty.io(1), Vulkan(1), Starling(1)

Inconsistent writing:

pygame, PyGame
Godot, Gobot
melonJS, MelonJS
MonoGame, Mono, Monogame

HTML canvas is not really a framework

**Comment by wonea** [comment]
I agree with removing HTML canvas, and correcting the inconsistent writing.

**Comment by Trilarion** [comment]
I did unify the spelling and removed HTML CANVAS, ZLIB, Gradle in #905.

Then we would be down to:

.NET Core(1), Allegro(8), BackBone.js(1), Box2D(1), Bullet3(1), Construct(1), Construct2(1), Cube 2 Engine(1), DIV Games Studio(5), Duality(1), EntityX(1), EnTT(1), Flash(1), GameMaker Studio(1), Godot(3), GTK+(1), Inform(1), Irrlicht(3), JavaFX(1), JMonkeyEngine(1), jQuery(2), Kylix(2), Laravel(1), LibGDX(6), Love3D(1), LÖVE(4), melonJS(2), Mono(1), MonoGame(4), ncurses(3), NeoAxis Engine(1), Netty.io(1), nya-engine(1), OGRE(7), OpenGL(13), Panda3D(2), PandaJS(1), Phaser(6), pixi.js(1), pygame(6), QB64(3), Qt(9), React(2), Redux(2), Rx.js(1), SDL(43), SDL2(43), Sea3D(1), SFML(9), Source SDK(1), Spring RTS Engine(1), Starling(1), SWT(1), three.js(3), Torque 3D(1), Tween.js(1), Unity(10), VDrift Engine(1), Vulkan(1), WebGL(9), XNA(3)

Is this worth having a list of known frameworks?

**Comment by Trilarion** [comment]
Do we want the list in the last message as list of known frameworks in danger?

**Comment by Trilarion** [comment]
is Vulkan a framework? I thought, it's an API. But then so is WebGL and we have it 9 times.

**Comment by cxong** [comment]
I guess so
I would like to eventually have a "did you mean X" message instead, based on best match, but I'm not sure if there's an npm package similar to https://github.com/seatgeek/fuzzywuzzy#process

**Comment by cxong** [comment]
The `framework` also includes engines. But they're all combined into one because the difference doesn't really matter, it's just metadata useful for developers.

**Comment by Trilarion** [comment]
Okay, then I will make a PR based on that list.

You could compute the Levenshtein distance in JS (see for example: https://stackoverflow.com/questions/10473745/compare-strings-javascript-return-of-likely). It looks like the code is not too long.
