### ISSUE TITLE
Add game form

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#911]
Adding games manually in the YAML can be error prone. I've started a project which aims to convert a pykwalify YAML schema into a webform, using osgameclones as the primary use case.

Check it out here: https://osgameclones.com/add_game.html

![Peek 2019-10-03 10-18](https://user-images.githubusercontent.com/1083215/66090676-c6ea3080-e5c7-11e9-9ec1-2e88697cb51c.gif)

Original game form here: https://osgameclones.com/add_original.html

In its current form I find it much easier to use than editing the YAML files directly, so hopefully this is useful for everyone else. Eventually I would like to integrate this with osgameclones directly, so that  users can load up the form from the page itself, to add new games or even edit existing games.

Here's a rough roadmap:

- [x] Complete all data types, including validation (e.g. select from valid licenses)
- [x] Create form for adding originals
- [x] Add to PyPI, build in osgameclones
- [x] Enhance games schema (e.g. add descriptions for fields)
- [ ] Add links to form in osgameclones page
- [x] Update all documentation to use the form instead

**Comment by cxong** [comment]
Please try it out and provide feedback!

**Comment by pehsa** [comment]
Quick test:
Only the name, originals, type and licence is required fields, now. Theres a chance someone add an entry without a URL and Repo link.

The updated field can provide a default value based on the user local time via JS

**Comment by cxong** [comment]
With the URL + repo: if this cannot be expressed in the YAML schema, then it can't be done (without hacks).

**Comment by pehsa** [comment]
No need to hack this. If you could provide the possibility to include user defined scripts e.g. "scripts" folder and the js files in this will included. Or just one script file which is always called.

I'm trying to think out of the OSGC scope for your project to be more general.

**Comment by cxong** [comment]
Added date picker. Defaulting to today would be nice but it's not applicable in the general case, and it isn't in and won't be added in pykwalify because it has nothing to do with validation. We may want to extend the schema to allow a `default` attribute.
