### ISSUE TITLE
Notification for direct repository URLs

### ISSUE THREAD

**Issue by pehsa** [opengaming/osgameclones#945]
We need some kind of notification for the user if the repo url is not a webpage or file. For example direct SVN or GIT access. ( SDL Asylum: svn://svn.code.sf.net/p/sdl-asylum/code/trunk ; PyBreak360: git://git.code.sf.net/p/pybreak360/code )

The browsers default not able to open these links.

Maybe warning when we add a game with direct repo link. Hard to test these links for live or dead link.

One more questionable is the FTP links (Agentadroids: ftp://ftp.tuxpaint.org/unix/agenda/agendaroids/src/agendaroids-2002.03.07.tar.gz ). For now everything is fine, but the Google wants to completely remove the FTP capabilities of the Chrome. I don't know exactly when this will be happening, but if the Chrome drop support, then the other browsers will follow.

**Comment by tomrndom** [comment]
I could add the check for FTP. 

On chromium and firefox latest's version the support has been removed by default due security issues.
