### ISSUE TITLE
Add Prom Week

### ISSUE THREAD

**Issue by DrAlta** [opengaming/osgameclones#984]
name: Prom Week
external:
  website: 'https://promweek.soe.ucsc.edu/'
platform:
- Web
meta:
  genre:
  - Simulation
  theme:
  - Dating

**Comment by neuromancer** [comment]
Is this open-source?

**Comment by cxong** [comment]
This is supposed to be an original game I think

**Comment by DrAlta** [comment]
@cxong  is right I meant add it as an original game.

**Comment by DrAlta** [comment]
> Is this open-source?

No, it's not but the engine is written in flash so you can decompile it and CiF uses XML to define actual social physics.
