### ISSUE TITLE
Removed Github repos

### ISSUE THREAD

**Issue by pehsa** [opengaming/osgameclones#989]
PKMN-FX https://github.com/jonasdemoor/PKMN-FX
Monsters and Mushrooms https://github.com/machinezilla/monsters_and_mushrooms (Fixed)
Seaquest https://github.com/brunocmorais/Seaquest 
One Way To Go https://github.com/purplehuman/onewaytogo (Fixed)
sentinel https://github.com/virgo47/sentinel
UiirJS https://github.com/ObviouslySorna/UiirJS

Harvest Cynthia #983

**Comment by cxong** [comment]
https://github.com/pycoder01/monsters_and_mushrooms
https://github.com/jaggedsoft/UiirJS

**Comment by Clownacy** [comment]
https://github.com/cuckydev/Cave-Story-Engine-2 is gone too. Official development was moved over to my repo - https://github.com/Clownacy/Cave-Story-Engine-2

**Comment by pehsa** [comment]
Fixed
